// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/perception_proto/perception_command.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "galbot/core_proto/header.pb.h"
#include "galbot/perception_proto/perception_result.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto;
namespace galbot {
namespace perception_proto {
class CommandReply;
class CommandReplyDefaultTypeInternal;
extern CommandReplyDefaultTypeInternal _CommandReply_default_instance_;
class ObjectMessage;
class ObjectMessageDefaultTypeInternal;
extern ObjectMessageDefaultTypeInternal _ObjectMessage_default_instance_;
class ServerCommand;
class ServerCommandDefaultTypeInternal;
extern ServerCommandDefaultTypeInternal _ServerCommand_default_instance_;
}  // namespace perception_proto
}  // namespace galbot
PROTOBUF_NAMESPACE_OPEN
template<> ::galbot::perception_proto::CommandReply* Arena::CreateMaybeMessage<::galbot::perception_proto::CommandReply>(Arena*);
template<> ::galbot::perception_proto::ObjectMessage* Arena::CreateMaybeMessage<::galbot::perception_proto::ObjectMessage>(Arena*);
template<> ::galbot::perception_proto::ServerCommand* Arena::CreateMaybeMessage<::galbot::perception_proto::ServerCommand>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace perception_proto {

// ===================================================================

class ObjectMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.perception_proto.ObjectMessage) */ {
 public:
  inline ObjectMessage() : ObjectMessage(nullptr) {}
  virtual ~ObjectMessage();

  ObjectMessage(const ObjectMessage& from);
  ObjectMessage(ObjectMessage&& from) noexcept
    : ObjectMessage() {
    *this = ::std::move(from);
  }

  inline ObjectMessage& operator=(const ObjectMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectMessage& operator=(ObjectMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ObjectMessage& default_instance();

  static inline const ObjectMessage* internal_default_instance() {
    return reinterpret_cast<const ObjectMessage*>(
               &_ObjectMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ObjectMessage& a, ObjectMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ObjectMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ObjectMessage* New() const final {
    return CreateMaybeMessage<ObjectMessage>(nullptr);
  }

  ObjectMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ObjectMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ObjectMessage& from);
  void MergeFrom(const ObjectMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.perception_proto.ObjectMessage";
  }
  protected:
  explicit ObjectMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto);
    return ::descriptor_table_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectTypeFieldNumber = 1,
    kXSizeFieldNumber = 2,
    kYSizeFieldNumber = 3,
    kZSizeFieldNumber = 4,
  };
  // string object_type = 1;
  void clear_object_type();
  const std::string& object_type() const;
  void set_object_type(const std::string& value);
  void set_object_type(std::string&& value);
  void set_object_type(const char* value);
  void set_object_type(const char* value, size_t size);
  std::string* mutable_object_type();
  std::string* release_object_type();
  void set_allocated_object_type(std::string* object_type);
  private:
  const std::string& _internal_object_type() const;
  void _internal_set_object_type(const std::string& value);
  std::string* _internal_mutable_object_type();
  public:

  // float x_size = 2;
  void clear_x_size();
  float x_size() const;
  void set_x_size(float value);
  private:
  float _internal_x_size() const;
  void _internal_set_x_size(float value);
  public:

  // float y_size = 3;
  void clear_y_size();
  float y_size() const;
  void set_y_size(float value);
  private:
  float _internal_y_size() const;
  void _internal_set_y_size(float value);
  public:

  // float z_size = 4;
  void clear_z_size();
  float z_size() const;
  void set_z_size(float value);
  private:
  float _internal_z_size() const;
  void _internal_set_z_size(float value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.perception_proto.ObjectMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr object_type_;
  float x_size_;
  float y_size_;
  float z_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto;
};
// -------------------------------------------------------------------

class ServerCommand PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.perception_proto.ServerCommand) */ {
 public:
  inline ServerCommand() : ServerCommand(nullptr) {}
  virtual ~ServerCommand();

  ServerCommand(const ServerCommand& from);
  ServerCommand(ServerCommand&& from) noexcept
    : ServerCommand() {
    *this = ::std::move(from);
  }

  inline ServerCommand& operator=(const ServerCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerCommand& operator=(ServerCommand&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ServerCommand& default_instance();

  static inline const ServerCommand* internal_default_instance() {
    return reinterpret_cast<const ServerCommand*>(
               &_ServerCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ServerCommand& a, ServerCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerCommand* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServerCommand* New() const final {
    return CreateMaybeMessage<ServerCommand>(nullptr);
  }

  ServerCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServerCommand>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ServerCommand& from);
  void MergeFrom(const ServerCommand& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerCommand* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.perception_proto.ServerCommand";
  }
  protected:
  explicit ServerCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto);
    return ::descriptor_table_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTemplateListFieldNumber = 14,
    kModelNameFieldNumber = 2,
    kActionFieldNumber = 3,
    kModelWeightsFieldNumber = 4,
    kTaskNameFieldNumber = 5,
    kSensorNameFieldNumber = 7,
    kClassNamesFieldNumber = 8,
    kObjectLabelIdFieldNumber = 12,
    kTaskIdFieldNumber = 13,
    kHeaderFieldNumber = 1,
    kPreResultFieldNumber = 10,
    kObjectMessageFieldNumber = 15,
    kIfTrackingFieldNumber = 6,
    kServerCommandCheckSignFieldNumber = 11,
    kSaveDataLevelFieldNumber = 9,
  };
  // repeated string template_list = 14;
  int template_list_size() const;
  private:
  int _internal_template_list_size() const;
  public:
  void clear_template_list();
  const std::string& template_list(int index) const;
  std::string* mutable_template_list(int index);
  void set_template_list(int index, const std::string& value);
  void set_template_list(int index, std::string&& value);
  void set_template_list(int index, const char* value);
  void set_template_list(int index, const char* value, size_t size);
  std::string* add_template_list();
  void add_template_list(const std::string& value);
  void add_template_list(std::string&& value);
  void add_template_list(const char* value);
  void add_template_list(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& template_list() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_template_list();
  private:
  const std::string& _internal_template_list(int index) const;
  std::string* _internal_add_template_list();
  public:

  // string model_name = 2;
  void clear_model_name();
  const std::string& model_name() const;
  void set_model_name(const std::string& value);
  void set_model_name(std::string&& value);
  void set_model_name(const char* value);
  void set_model_name(const char* value, size_t size);
  std::string* mutable_model_name();
  std::string* release_model_name();
  void set_allocated_model_name(std::string* model_name);
  private:
  const std::string& _internal_model_name() const;
  void _internal_set_model_name(const std::string& value);
  std::string* _internal_mutable_model_name();
  public:

  // string action = 3;
  void clear_action();
  const std::string& action() const;
  void set_action(const std::string& value);
  void set_action(std::string&& value);
  void set_action(const char* value);
  void set_action(const char* value, size_t size);
  std::string* mutable_action();
  std::string* release_action();
  void set_allocated_action(std::string* action);
  private:
  const std::string& _internal_action() const;
  void _internal_set_action(const std::string& value);
  std::string* _internal_mutable_action();
  public:

  // string model_weights = 4;
  void clear_model_weights();
  const std::string& model_weights() const;
  void set_model_weights(const std::string& value);
  void set_model_weights(std::string&& value);
  void set_model_weights(const char* value);
  void set_model_weights(const char* value, size_t size);
  std::string* mutable_model_weights();
  std::string* release_model_weights();
  void set_allocated_model_weights(std::string* model_weights);
  private:
  const std::string& _internal_model_weights() const;
  void _internal_set_model_weights(const std::string& value);
  std::string* _internal_mutable_model_weights();
  public:

  // string task_name = 5;
  void clear_task_name();
  const std::string& task_name() const;
  void set_task_name(const std::string& value);
  void set_task_name(std::string&& value);
  void set_task_name(const char* value);
  void set_task_name(const char* value, size_t size);
  std::string* mutable_task_name();
  std::string* release_task_name();
  void set_allocated_task_name(std::string* task_name);
  private:
  const std::string& _internal_task_name() const;
  void _internal_set_task_name(const std::string& value);
  std::string* _internal_mutable_task_name();
  public:

  // string sensor_name = 7;
  void clear_sensor_name();
  const std::string& sensor_name() const;
  void set_sensor_name(const std::string& value);
  void set_sensor_name(std::string&& value);
  void set_sensor_name(const char* value);
  void set_sensor_name(const char* value, size_t size);
  std::string* mutable_sensor_name();
  std::string* release_sensor_name();
  void set_allocated_sensor_name(std::string* sensor_name);
  private:
  const std::string& _internal_sensor_name() const;
  void _internal_set_sensor_name(const std::string& value);
  std::string* _internal_mutable_sensor_name();
  public:

  // string class_names = 8;
  void clear_class_names();
  const std::string& class_names() const;
  void set_class_names(const std::string& value);
  void set_class_names(std::string&& value);
  void set_class_names(const char* value);
  void set_class_names(const char* value, size_t size);
  std::string* mutable_class_names();
  std::string* release_class_names();
  void set_allocated_class_names(std::string* class_names);
  private:
  const std::string& _internal_class_names() const;
  void _internal_set_class_names(const std::string& value);
  std::string* _internal_mutable_class_names();
  public:

  // string object_label_id = 12;
  void clear_object_label_id();
  const std::string& object_label_id() const;
  void set_object_label_id(const std::string& value);
  void set_object_label_id(std::string&& value);
  void set_object_label_id(const char* value);
  void set_object_label_id(const char* value, size_t size);
  std::string* mutable_object_label_id();
  std::string* release_object_label_id();
  void set_allocated_object_label_id(std::string* object_label_id);
  private:
  const std::string& _internal_object_label_id() const;
  void _internal_set_object_label_id(const std::string& value);
  std::string* _internal_mutable_object_label_id();
  public:

  // string task_id = 13;
  void clear_task_id();
  const std::string& task_id() const;
  void set_task_id(const std::string& value);
  void set_task_id(std::string&& value);
  void set_task_id(const char* value);
  void set_task_id(const char* value, size_t size);
  std::string* mutable_task_id();
  std::string* release_task_id();
  void set_allocated_task_id(std::string* task_id);
  private:
  const std::string& _internal_task_id() const;
  void _internal_set_task_id(const std::string& value);
  std::string* _internal_mutable_task_id();
  public:

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // .galbot.perception_proto.DetectionResult pre_result = 10;
  bool has_pre_result() const;
  private:
  bool _internal_has_pre_result() const;
  public:
  void clear_pre_result();
  const ::galbot::perception_proto::DetectionResult& pre_result() const;
  ::galbot::perception_proto::DetectionResult* release_pre_result();
  ::galbot::perception_proto::DetectionResult* mutable_pre_result();
  void set_allocated_pre_result(::galbot::perception_proto::DetectionResult* pre_result);
  private:
  const ::galbot::perception_proto::DetectionResult& _internal_pre_result() const;
  ::galbot::perception_proto::DetectionResult* _internal_mutable_pre_result();
  public:
  void unsafe_arena_set_allocated_pre_result(
      ::galbot::perception_proto::DetectionResult* pre_result);
  ::galbot::perception_proto::DetectionResult* unsafe_arena_release_pre_result();

  // .galbot.perception_proto.ObjectMessage object_message = 15;
  bool has_object_message() const;
  private:
  bool _internal_has_object_message() const;
  public:
  void clear_object_message();
  const ::galbot::perception_proto::ObjectMessage& object_message() const;
  ::galbot::perception_proto::ObjectMessage* release_object_message();
  ::galbot::perception_proto::ObjectMessage* mutable_object_message();
  void set_allocated_object_message(::galbot::perception_proto::ObjectMessage* object_message);
  private:
  const ::galbot::perception_proto::ObjectMessage& _internal_object_message() const;
  ::galbot::perception_proto::ObjectMessage* _internal_mutable_object_message();
  public:
  void unsafe_arena_set_allocated_object_message(
      ::galbot::perception_proto::ObjectMessage* object_message);
  ::galbot::perception_proto::ObjectMessage* unsafe_arena_release_object_message();

  // bool if_tracking = 6;
  void clear_if_tracking();
  bool if_tracking() const;
  void set_if_tracking(bool value);
  private:
  bool _internal_if_tracking() const;
  void _internal_set_if_tracking(bool value);
  public:

  // bool server_command_check_sign = 11;
  void clear_server_command_check_sign();
  bool server_command_check_sign() const;
  void set_server_command_check_sign(bool value);
  private:
  bool _internal_server_command_check_sign() const;
  void _internal_set_server_command_check_sign(bool value);
  public:

  // int32 save_data_level = 9;
  void clear_save_data_level();
  ::PROTOBUF_NAMESPACE_ID::int32 save_data_level() const;
  void set_save_data_level(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_save_data_level() const;
  void _internal_set_save_data_level(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.perception_proto.ServerCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> template_list_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr model_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr action_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr model_weights_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sensor_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr class_names_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr object_label_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_id_;
  ::galbot::core_proto::Header* header_;
  ::galbot::perception_proto::DetectionResult* pre_result_;
  ::galbot::perception_proto::ObjectMessage* object_message_;
  bool if_tracking_;
  bool server_command_check_sign_;
  ::PROTOBUF_NAMESPACE_ID::int32 save_data_level_;
  friend struct ::TableStruct_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto;
};
// -------------------------------------------------------------------

class CommandReply PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.perception_proto.CommandReply) */ {
 public:
  inline CommandReply() : CommandReply(nullptr) {}
  virtual ~CommandReply();

  CommandReply(const CommandReply& from);
  CommandReply(CommandReply&& from) noexcept
    : CommandReply() {
    *this = ::std::move(from);
  }

  inline CommandReply& operator=(const CommandReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline CommandReply& operator=(CommandReply&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CommandReply& default_instance();

  static inline const CommandReply* internal_default_instance() {
    return reinterpret_cast<const CommandReply*>(
               &_CommandReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CommandReply& a, CommandReply& b) {
    a.Swap(&b);
  }
  inline void Swap(CommandReply* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CommandReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CommandReply* New() const final {
    return CreateMaybeMessage<CommandReply>(nullptr);
  }

  CommandReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CommandReply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CommandReply& from);
  void MergeFrom(const CommandReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CommandReply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.perception_proto.CommandReply";
  }
  protected:
  explicit CommandReply(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto);
    return ::descriptor_table_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kModelNameFieldNumber = 2,
    kTaskNameFieldNumber = 3,
    kHeaderFieldNumber = 1,
    kStatusFieldNumber = 4,
  };
  // string model_name = 2;
  void clear_model_name();
  const std::string& model_name() const;
  void set_model_name(const std::string& value);
  void set_model_name(std::string&& value);
  void set_model_name(const char* value);
  void set_model_name(const char* value, size_t size);
  std::string* mutable_model_name();
  std::string* release_model_name();
  void set_allocated_model_name(std::string* model_name);
  private:
  const std::string& _internal_model_name() const;
  void _internal_set_model_name(const std::string& value);
  std::string* _internal_mutable_model_name();
  public:

  // string task_name = 3;
  void clear_task_name();
  const std::string& task_name() const;
  void set_task_name(const std::string& value);
  void set_task_name(std::string&& value);
  void set_task_name(const char* value);
  void set_task_name(const char* value, size_t size);
  std::string* mutable_task_name();
  std::string* release_task_name();
  void set_allocated_task_name(std::string* task_name);
  private:
  const std::string& _internal_task_name() const;
  void _internal_set_task_name(const std::string& value);
  std::string* _internal_mutable_task_name();
  public:

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // bool status = 4;
  void clear_status();
  bool status() const;
  void set_status(bool value);
  private:
  bool _internal_status() const;
  void _internal_set_status(bool value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.perception_proto.CommandReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr model_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_name_;
  ::galbot::core_proto::Header* header_;
  bool status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ObjectMessage

// string object_type = 1;
inline void ObjectMessage::clear_object_type() {
  object_type_.ClearToEmpty();
}
inline const std::string& ObjectMessage::object_type() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ObjectMessage.object_type)
  return _internal_object_type();
}
inline void ObjectMessage::set_object_type(const std::string& value) {
  _internal_set_object_type(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ObjectMessage.object_type)
}
inline std::string* ObjectMessage::mutable_object_type() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.ObjectMessage.object_type)
  return _internal_mutable_object_type();
}
inline const std::string& ObjectMessage::_internal_object_type() const {
  return object_type_.Get();
}
inline void ObjectMessage::_internal_set_object_type(const std::string& value) {
  
  object_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ObjectMessage::set_object_type(std::string&& value) {
  
  object_type_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.perception_proto.ObjectMessage.object_type)
}
inline void ObjectMessage::set_object_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  object_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.perception_proto.ObjectMessage.object_type)
}
inline void ObjectMessage::set_object_type(const char* value,
    size_t size) {
  
  object_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.perception_proto.ObjectMessage.object_type)
}
inline std::string* ObjectMessage::_internal_mutable_object_type() {
  
  return object_type_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ObjectMessage::release_object_type() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.ObjectMessage.object_type)
  return object_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ObjectMessage::set_allocated_object_type(std::string* object_type) {
  if (object_type != nullptr) {
    
  } else {
    
  }
  object_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), object_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.ObjectMessage.object_type)
}

// float x_size = 2;
inline void ObjectMessage::clear_x_size() {
  x_size_ = 0;
}
inline float ObjectMessage::_internal_x_size() const {
  return x_size_;
}
inline float ObjectMessage::x_size() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ObjectMessage.x_size)
  return _internal_x_size();
}
inline void ObjectMessage::_internal_set_x_size(float value) {
  
  x_size_ = value;
}
inline void ObjectMessage::set_x_size(float value) {
  _internal_set_x_size(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ObjectMessage.x_size)
}

// float y_size = 3;
inline void ObjectMessage::clear_y_size() {
  y_size_ = 0;
}
inline float ObjectMessage::_internal_y_size() const {
  return y_size_;
}
inline float ObjectMessage::y_size() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ObjectMessage.y_size)
  return _internal_y_size();
}
inline void ObjectMessage::_internal_set_y_size(float value) {
  
  y_size_ = value;
}
inline void ObjectMessage::set_y_size(float value) {
  _internal_set_y_size(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ObjectMessage.y_size)
}

// float z_size = 4;
inline void ObjectMessage::clear_z_size() {
  z_size_ = 0;
}
inline float ObjectMessage::_internal_z_size() const {
  return z_size_;
}
inline float ObjectMessage::z_size() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ObjectMessage.z_size)
  return _internal_z_size();
}
inline void ObjectMessage::_internal_set_z_size(float value) {
  
  z_size_ = value;
}
inline void ObjectMessage::set_z_size(float value) {
  _internal_set_z_size(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ObjectMessage.z_size)
}

// -------------------------------------------------------------------

// ServerCommand

// .galbot.core_proto.Header header = 1;
inline bool ServerCommand::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool ServerCommand::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& ServerCommand::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& ServerCommand::header() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.header)
  return _internal_header();
}
inline void ServerCommand::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.perception_proto.ServerCommand.header)
}
inline ::galbot::core_proto::Header* ServerCommand::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* ServerCommand::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.ServerCommand.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* ServerCommand::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* ServerCommand::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.ServerCommand.header)
  return _internal_mutable_header();
}
inline void ServerCommand::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.ServerCommand.header)
}

// string model_name = 2;
inline void ServerCommand::clear_model_name() {
  model_name_.ClearToEmpty();
}
inline const std::string& ServerCommand::model_name() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.model_name)
  return _internal_model_name();
}
inline void ServerCommand::set_model_name(const std::string& value) {
  _internal_set_model_name(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ServerCommand.model_name)
}
inline std::string* ServerCommand::mutable_model_name() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.ServerCommand.model_name)
  return _internal_mutable_model_name();
}
inline const std::string& ServerCommand::_internal_model_name() const {
  return model_name_.Get();
}
inline void ServerCommand::_internal_set_model_name(const std::string& value) {
  
  model_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ServerCommand::set_model_name(std::string&& value) {
  
  model_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.perception_proto.ServerCommand.model_name)
}
inline void ServerCommand::set_model_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  model_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.perception_proto.ServerCommand.model_name)
}
inline void ServerCommand::set_model_name(const char* value,
    size_t size) {
  
  model_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.perception_proto.ServerCommand.model_name)
}
inline std::string* ServerCommand::_internal_mutable_model_name() {
  
  return model_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ServerCommand::release_model_name() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.ServerCommand.model_name)
  return model_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServerCommand::set_allocated_model_name(std::string* model_name) {
  if (model_name != nullptr) {
    
  } else {
    
  }
  model_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), model_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.ServerCommand.model_name)
}

// string action = 3;
inline void ServerCommand::clear_action() {
  action_.ClearToEmpty();
}
inline const std::string& ServerCommand::action() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.action)
  return _internal_action();
}
inline void ServerCommand::set_action(const std::string& value) {
  _internal_set_action(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ServerCommand.action)
}
inline std::string* ServerCommand::mutable_action() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.ServerCommand.action)
  return _internal_mutable_action();
}
inline const std::string& ServerCommand::_internal_action() const {
  return action_.Get();
}
inline void ServerCommand::_internal_set_action(const std::string& value) {
  
  action_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ServerCommand::set_action(std::string&& value) {
  
  action_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.perception_proto.ServerCommand.action)
}
inline void ServerCommand::set_action(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  action_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.perception_proto.ServerCommand.action)
}
inline void ServerCommand::set_action(const char* value,
    size_t size) {
  
  action_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.perception_proto.ServerCommand.action)
}
inline std::string* ServerCommand::_internal_mutable_action() {
  
  return action_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ServerCommand::release_action() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.ServerCommand.action)
  return action_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServerCommand::set_allocated_action(std::string* action) {
  if (action != nullptr) {
    
  } else {
    
  }
  action_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), action,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.ServerCommand.action)
}

// string model_weights = 4;
inline void ServerCommand::clear_model_weights() {
  model_weights_.ClearToEmpty();
}
inline const std::string& ServerCommand::model_weights() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.model_weights)
  return _internal_model_weights();
}
inline void ServerCommand::set_model_weights(const std::string& value) {
  _internal_set_model_weights(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ServerCommand.model_weights)
}
inline std::string* ServerCommand::mutable_model_weights() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.ServerCommand.model_weights)
  return _internal_mutable_model_weights();
}
inline const std::string& ServerCommand::_internal_model_weights() const {
  return model_weights_.Get();
}
inline void ServerCommand::_internal_set_model_weights(const std::string& value) {
  
  model_weights_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ServerCommand::set_model_weights(std::string&& value) {
  
  model_weights_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.perception_proto.ServerCommand.model_weights)
}
inline void ServerCommand::set_model_weights(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  model_weights_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.perception_proto.ServerCommand.model_weights)
}
inline void ServerCommand::set_model_weights(const char* value,
    size_t size) {
  
  model_weights_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.perception_proto.ServerCommand.model_weights)
}
inline std::string* ServerCommand::_internal_mutable_model_weights() {
  
  return model_weights_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ServerCommand::release_model_weights() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.ServerCommand.model_weights)
  return model_weights_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServerCommand::set_allocated_model_weights(std::string* model_weights) {
  if (model_weights != nullptr) {
    
  } else {
    
  }
  model_weights_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), model_weights,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.ServerCommand.model_weights)
}

// string task_name = 5;
inline void ServerCommand::clear_task_name() {
  task_name_.ClearToEmpty();
}
inline const std::string& ServerCommand::task_name() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.task_name)
  return _internal_task_name();
}
inline void ServerCommand::set_task_name(const std::string& value) {
  _internal_set_task_name(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ServerCommand.task_name)
}
inline std::string* ServerCommand::mutable_task_name() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.ServerCommand.task_name)
  return _internal_mutable_task_name();
}
inline const std::string& ServerCommand::_internal_task_name() const {
  return task_name_.Get();
}
inline void ServerCommand::_internal_set_task_name(const std::string& value) {
  
  task_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ServerCommand::set_task_name(std::string&& value) {
  
  task_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.perception_proto.ServerCommand.task_name)
}
inline void ServerCommand::set_task_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  task_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.perception_proto.ServerCommand.task_name)
}
inline void ServerCommand::set_task_name(const char* value,
    size_t size) {
  
  task_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.perception_proto.ServerCommand.task_name)
}
inline std::string* ServerCommand::_internal_mutable_task_name() {
  
  return task_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ServerCommand::release_task_name() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.ServerCommand.task_name)
  return task_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServerCommand::set_allocated_task_name(std::string* task_name) {
  if (task_name != nullptr) {
    
  } else {
    
  }
  task_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), task_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.ServerCommand.task_name)
}

// bool if_tracking = 6;
inline void ServerCommand::clear_if_tracking() {
  if_tracking_ = false;
}
inline bool ServerCommand::_internal_if_tracking() const {
  return if_tracking_;
}
inline bool ServerCommand::if_tracking() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.if_tracking)
  return _internal_if_tracking();
}
inline void ServerCommand::_internal_set_if_tracking(bool value) {
  
  if_tracking_ = value;
}
inline void ServerCommand::set_if_tracking(bool value) {
  _internal_set_if_tracking(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ServerCommand.if_tracking)
}

// string sensor_name = 7;
inline void ServerCommand::clear_sensor_name() {
  sensor_name_.ClearToEmpty();
}
inline const std::string& ServerCommand::sensor_name() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.sensor_name)
  return _internal_sensor_name();
}
inline void ServerCommand::set_sensor_name(const std::string& value) {
  _internal_set_sensor_name(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ServerCommand.sensor_name)
}
inline std::string* ServerCommand::mutable_sensor_name() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.ServerCommand.sensor_name)
  return _internal_mutable_sensor_name();
}
inline const std::string& ServerCommand::_internal_sensor_name() const {
  return sensor_name_.Get();
}
inline void ServerCommand::_internal_set_sensor_name(const std::string& value) {
  
  sensor_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ServerCommand::set_sensor_name(std::string&& value) {
  
  sensor_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.perception_proto.ServerCommand.sensor_name)
}
inline void ServerCommand::set_sensor_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sensor_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.perception_proto.ServerCommand.sensor_name)
}
inline void ServerCommand::set_sensor_name(const char* value,
    size_t size) {
  
  sensor_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.perception_proto.ServerCommand.sensor_name)
}
inline std::string* ServerCommand::_internal_mutable_sensor_name() {
  
  return sensor_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ServerCommand::release_sensor_name() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.ServerCommand.sensor_name)
  return sensor_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServerCommand::set_allocated_sensor_name(std::string* sensor_name) {
  if (sensor_name != nullptr) {
    
  } else {
    
  }
  sensor_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sensor_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.ServerCommand.sensor_name)
}

// string class_names = 8;
inline void ServerCommand::clear_class_names() {
  class_names_.ClearToEmpty();
}
inline const std::string& ServerCommand::class_names() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.class_names)
  return _internal_class_names();
}
inline void ServerCommand::set_class_names(const std::string& value) {
  _internal_set_class_names(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ServerCommand.class_names)
}
inline std::string* ServerCommand::mutable_class_names() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.ServerCommand.class_names)
  return _internal_mutable_class_names();
}
inline const std::string& ServerCommand::_internal_class_names() const {
  return class_names_.Get();
}
inline void ServerCommand::_internal_set_class_names(const std::string& value) {
  
  class_names_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ServerCommand::set_class_names(std::string&& value) {
  
  class_names_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.perception_proto.ServerCommand.class_names)
}
inline void ServerCommand::set_class_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  class_names_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.perception_proto.ServerCommand.class_names)
}
inline void ServerCommand::set_class_names(const char* value,
    size_t size) {
  
  class_names_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.perception_proto.ServerCommand.class_names)
}
inline std::string* ServerCommand::_internal_mutable_class_names() {
  
  return class_names_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ServerCommand::release_class_names() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.ServerCommand.class_names)
  return class_names_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServerCommand::set_allocated_class_names(std::string* class_names) {
  if (class_names != nullptr) {
    
  } else {
    
  }
  class_names_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), class_names,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.ServerCommand.class_names)
}

// int32 save_data_level = 9;
inline void ServerCommand::clear_save_data_level() {
  save_data_level_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ServerCommand::_internal_save_data_level() const {
  return save_data_level_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ServerCommand::save_data_level() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.save_data_level)
  return _internal_save_data_level();
}
inline void ServerCommand::_internal_set_save_data_level(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  save_data_level_ = value;
}
inline void ServerCommand::set_save_data_level(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_save_data_level(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ServerCommand.save_data_level)
}

// .galbot.perception_proto.DetectionResult pre_result = 10;
inline bool ServerCommand::_internal_has_pre_result() const {
  return this != internal_default_instance() && pre_result_ != nullptr;
}
inline bool ServerCommand::has_pre_result() const {
  return _internal_has_pre_result();
}
inline const ::galbot::perception_proto::DetectionResult& ServerCommand::_internal_pre_result() const {
  const ::galbot::perception_proto::DetectionResult* p = pre_result_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::perception_proto::DetectionResult&>(
      ::galbot::perception_proto::_DetectionResult_default_instance_);
}
inline const ::galbot::perception_proto::DetectionResult& ServerCommand::pre_result() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.pre_result)
  return _internal_pre_result();
}
inline void ServerCommand::unsafe_arena_set_allocated_pre_result(
    ::galbot::perception_proto::DetectionResult* pre_result) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pre_result_);
  }
  pre_result_ = pre_result;
  if (pre_result) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.perception_proto.ServerCommand.pre_result)
}
inline ::galbot::perception_proto::DetectionResult* ServerCommand::release_pre_result() {
  
  ::galbot::perception_proto::DetectionResult* temp = pre_result_;
  pre_result_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::perception_proto::DetectionResult* ServerCommand::unsafe_arena_release_pre_result() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.ServerCommand.pre_result)
  
  ::galbot::perception_proto::DetectionResult* temp = pre_result_;
  pre_result_ = nullptr;
  return temp;
}
inline ::galbot::perception_proto::DetectionResult* ServerCommand::_internal_mutable_pre_result() {
  
  if (pre_result_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::perception_proto::DetectionResult>(GetArena());
    pre_result_ = p;
  }
  return pre_result_;
}
inline ::galbot::perception_proto::DetectionResult* ServerCommand::mutable_pre_result() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.ServerCommand.pre_result)
  return _internal_mutable_pre_result();
}
inline void ServerCommand::set_allocated_pre_result(::galbot::perception_proto::DetectionResult* pre_result) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(pre_result_);
  }
  if (pre_result) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pre_result)->GetArena();
    if (message_arena != submessage_arena) {
      pre_result = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pre_result, submessage_arena);
    }
    
  } else {
    
  }
  pre_result_ = pre_result;
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.ServerCommand.pre_result)
}

// bool server_command_check_sign = 11;
inline void ServerCommand::clear_server_command_check_sign() {
  server_command_check_sign_ = false;
}
inline bool ServerCommand::_internal_server_command_check_sign() const {
  return server_command_check_sign_;
}
inline bool ServerCommand::server_command_check_sign() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.server_command_check_sign)
  return _internal_server_command_check_sign();
}
inline void ServerCommand::_internal_set_server_command_check_sign(bool value) {
  
  server_command_check_sign_ = value;
}
inline void ServerCommand::set_server_command_check_sign(bool value) {
  _internal_set_server_command_check_sign(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ServerCommand.server_command_check_sign)
}

// string object_label_id = 12;
inline void ServerCommand::clear_object_label_id() {
  object_label_id_.ClearToEmpty();
}
inline const std::string& ServerCommand::object_label_id() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.object_label_id)
  return _internal_object_label_id();
}
inline void ServerCommand::set_object_label_id(const std::string& value) {
  _internal_set_object_label_id(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ServerCommand.object_label_id)
}
inline std::string* ServerCommand::mutable_object_label_id() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.ServerCommand.object_label_id)
  return _internal_mutable_object_label_id();
}
inline const std::string& ServerCommand::_internal_object_label_id() const {
  return object_label_id_.Get();
}
inline void ServerCommand::_internal_set_object_label_id(const std::string& value) {
  
  object_label_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ServerCommand::set_object_label_id(std::string&& value) {
  
  object_label_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.perception_proto.ServerCommand.object_label_id)
}
inline void ServerCommand::set_object_label_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  object_label_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.perception_proto.ServerCommand.object_label_id)
}
inline void ServerCommand::set_object_label_id(const char* value,
    size_t size) {
  
  object_label_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.perception_proto.ServerCommand.object_label_id)
}
inline std::string* ServerCommand::_internal_mutable_object_label_id() {
  
  return object_label_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ServerCommand::release_object_label_id() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.ServerCommand.object_label_id)
  return object_label_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServerCommand::set_allocated_object_label_id(std::string* object_label_id) {
  if (object_label_id != nullptr) {
    
  } else {
    
  }
  object_label_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), object_label_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.ServerCommand.object_label_id)
}

// string task_id = 13;
inline void ServerCommand::clear_task_id() {
  task_id_.ClearToEmpty();
}
inline const std::string& ServerCommand::task_id() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.task_id)
  return _internal_task_id();
}
inline void ServerCommand::set_task_id(const std::string& value) {
  _internal_set_task_id(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ServerCommand.task_id)
}
inline std::string* ServerCommand::mutable_task_id() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.ServerCommand.task_id)
  return _internal_mutable_task_id();
}
inline const std::string& ServerCommand::_internal_task_id() const {
  return task_id_.Get();
}
inline void ServerCommand::_internal_set_task_id(const std::string& value) {
  
  task_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ServerCommand::set_task_id(std::string&& value) {
  
  task_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.perception_proto.ServerCommand.task_id)
}
inline void ServerCommand::set_task_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  task_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.perception_proto.ServerCommand.task_id)
}
inline void ServerCommand::set_task_id(const char* value,
    size_t size) {
  
  task_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.perception_proto.ServerCommand.task_id)
}
inline std::string* ServerCommand::_internal_mutable_task_id() {
  
  return task_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ServerCommand::release_task_id() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.ServerCommand.task_id)
  return task_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServerCommand::set_allocated_task_id(std::string* task_id) {
  if (task_id != nullptr) {
    
  } else {
    
  }
  task_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), task_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.ServerCommand.task_id)
}

// repeated string template_list = 14;
inline int ServerCommand::_internal_template_list_size() const {
  return template_list_.size();
}
inline int ServerCommand::template_list_size() const {
  return _internal_template_list_size();
}
inline void ServerCommand::clear_template_list() {
  template_list_.Clear();
}
inline std::string* ServerCommand::add_template_list() {
  // @@protoc_insertion_point(field_add_mutable:galbot.perception_proto.ServerCommand.template_list)
  return _internal_add_template_list();
}
inline const std::string& ServerCommand::_internal_template_list(int index) const {
  return template_list_.Get(index);
}
inline const std::string& ServerCommand::template_list(int index) const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.template_list)
  return _internal_template_list(index);
}
inline std::string* ServerCommand::mutable_template_list(int index) {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.ServerCommand.template_list)
  return template_list_.Mutable(index);
}
inline void ServerCommand::set_template_list(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ServerCommand.template_list)
  template_list_.Mutable(index)->assign(value);
}
inline void ServerCommand::set_template_list(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:galbot.perception_proto.ServerCommand.template_list)
  template_list_.Mutable(index)->assign(std::move(value));
}
inline void ServerCommand::set_template_list(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  template_list_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:galbot.perception_proto.ServerCommand.template_list)
}
inline void ServerCommand::set_template_list(int index, const char* value, size_t size) {
  template_list_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:galbot.perception_proto.ServerCommand.template_list)
}
inline std::string* ServerCommand::_internal_add_template_list() {
  return template_list_.Add();
}
inline void ServerCommand::add_template_list(const std::string& value) {
  template_list_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:galbot.perception_proto.ServerCommand.template_list)
}
inline void ServerCommand::add_template_list(std::string&& value) {
  template_list_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:galbot.perception_proto.ServerCommand.template_list)
}
inline void ServerCommand::add_template_list(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  template_list_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:galbot.perception_proto.ServerCommand.template_list)
}
inline void ServerCommand::add_template_list(const char* value, size_t size) {
  template_list_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:galbot.perception_proto.ServerCommand.template_list)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ServerCommand::template_list() const {
  // @@protoc_insertion_point(field_list:galbot.perception_proto.ServerCommand.template_list)
  return template_list_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ServerCommand::mutable_template_list() {
  // @@protoc_insertion_point(field_mutable_list:galbot.perception_proto.ServerCommand.template_list)
  return &template_list_;
}

// .galbot.perception_proto.ObjectMessage object_message = 15;
inline bool ServerCommand::_internal_has_object_message() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || object_message_ != nullptr);
  return value;
}
inline bool ServerCommand::has_object_message() const {
  return _internal_has_object_message();
}
inline void ServerCommand::clear_object_message() {
  if (GetArena() == nullptr && object_message_ != nullptr) {
    delete object_message_;
  }
  object_message_ = nullptr;
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::galbot::perception_proto::ObjectMessage& ServerCommand::_internal_object_message() const {
  const ::galbot::perception_proto::ObjectMessage* p = object_message_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::perception_proto::ObjectMessage&>(
      ::galbot::perception_proto::_ObjectMessage_default_instance_);
}
inline const ::galbot::perception_proto::ObjectMessage& ServerCommand::object_message() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.ServerCommand.object_message)
  return _internal_object_message();
}
inline void ServerCommand::unsafe_arena_set_allocated_object_message(
    ::galbot::perception_proto::ObjectMessage* object_message) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(object_message_);
  }
  object_message_ = object_message;
  if (object_message) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.perception_proto.ServerCommand.object_message)
}
inline ::galbot::perception_proto::ObjectMessage* ServerCommand::release_object_message() {
  _has_bits_[0] &= ~0x00000001u;
  ::galbot::perception_proto::ObjectMessage* temp = object_message_;
  object_message_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::perception_proto::ObjectMessage* ServerCommand::unsafe_arena_release_object_message() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.ServerCommand.object_message)
  _has_bits_[0] &= ~0x00000001u;
  ::galbot::perception_proto::ObjectMessage* temp = object_message_;
  object_message_ = nullptr;
  return temp;
}
inline ::galbot::perception_proto::ObjectMessage* ServerCommand::_internal_mutable_object_message() {
  _has_bits_[0] |= 0x00000001u;
  if (object_message_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::perception_proto::ObjectMessage>(GetArena());
    object_message_ = p;
  }
  return object_message_;
}
inline ::galbot::perception_proto::ObjectMessage* ServerCommand::mutable_object_message() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.ServerCommand.object_message)
  return _internal_mutable_object_message();
}
inline void ServerCommand::set_allocated_object_message(::galbot::perception_proto::ObjectMessage* object_message) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete object_message_;
  }
  if (object_message) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(object_message);
    if (message_arena != submessage_arena) {
      object_message = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, object_message, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  object_message_ = object_message;
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.ServerCommand.object_message)
}

// -------------------------------------------------------------------

// CommandReply

// .galbot.core_proto.Header header = 1;
inline bool CommandReply::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool CommandReply::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& CommandReply::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& CommandReply::header() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.CommandReply.header)
  return _internal_header();
}
inline void CommandReply::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.perception_proto.CommandReply.header)
}
inline ::galbot::core_proto::Header* CommandReply::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* CommandReply::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.CommandReply.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* CommandReply::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* CommandReply::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.CommandReply.header)
  return _internal_mutable_header();
}
inline void CommandReply::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.CommandReply.header)
}

// string model_name = 2;
inline void CommandReply::clear_model_name() {
  model_name_.ClearToEmpty();
}
inline const std::string& CommandReply::model_name() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.CommandReply.model_name)
  return _internal_model_name();
}
inline void CommandReply::set_model_name(const std::string& value) {
  _internal_set_model_name(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.CommandReply.model_name)
}
inline std::string* CommandReply::mutable_model_name() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.CommandReply.model_name)
  return _internal_mutable_model_name();
}
inline const std::string& CommandReply::_internal_model_name() const {
  return model_name_.Get();
}
inline void CommandReply::_internal_set_model_name(const std::string& value) {
  
  model_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CommandReply::set_model_name(std::string&& value) {
  
  model_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.perception_proto.CommandReply.model_name)
}
inline void CommandReply::set_model_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  model_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.perception_proto.CommandReply.model_name)
}
inline void CommandReply::set_model_name(const char* value,
    size_t size) {
  
  model_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.perception_proto.CommandReply.model_name)
}
inline std::string* CommandReply::_internal_mutable_model_name() {
  
  return model_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CommandReply::release_model_name() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.CommandReply.model_name)
  return model_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CommandReply::set_allocated_model_name(std::string* model_name) {
  if (model_name != nullptr) {
    
  } else {
    
  }
  model_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), model_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.CommandReply.model_name)
}

// string task_name = 3;
inline void CommandReply::clear_task_name() {
  task_name_.ClearToEmpty();
}
inline const std::string& CommandReply::task_name() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.CommandReply.task_name)
  return _internal_task_name();
}
inline void CommandReply::set_task_name(const std::string& value) {
  _internal_set_task_name(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.CommandReply.task_name)
}
inline std::string* CommandReply::mutable_task_name() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.CommandReply.task_name)
  return _internal_mutable_task_name();
}
inline const std::string& CommandReply::_internal_task_name() const {
  return task_name_.Get();
}
inline void CommandReply::_internal_set_task_name(const std::string& value) {
  
  task_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CommandReply::set_task_name(std::string&& value) {
  
  task_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.perception_proto.CommandReply.task_name)
}
inline void CommandReply::set_task_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  task_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.perception_proto.CommandReply.task_name)
}
inline void CommandReply::set_task_name(const char* value,
    size_t size) {
  
  task_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.perception_proto.CommandReply.task_name)
}
inline std::string* CommandReply::_internal_mutable_task_name() {
  
  return task_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CommandReply::release_task_name() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.CommandReply.task_name)
  return task_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CommandReply::set_allocated_task_name(std::string* task_name) {
  if (task_name != nullptr) {
    
  } else {
    
  }
  task_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), task_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.CommandReply.task_name)
}

// bool status = 4;
inline void CommandReply::clear_status() {
  status_ = false;
}
inline bool CommandReply::_internal_status() const {
  return status_;
}
inline bool CommandReply::status() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.CommandReply.status)
  return _internal_status();
}
inline void CommandReply::_internal_set_status(bool value) {
  
  status_ = value;
}
inline void CommandReply::set_status(bool value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.CommandReply.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace perception_proto
}  // namespace galbot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fperception_5fproto_2fperception_5fcommand_2eproto
