// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/system_proto/diagnose_proto/mode_type.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fsystem_5fproto_2fdiagnose_5fproto_2fmode_5ftype_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fsystem_5fproto_2fdiagnose_5fproto_2fmode_5ftype_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fsystem_5fproto_2fdiagnose_5fproto_2fmode_5ftype_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fsystem_5fproto_2fdiagnose_5fproto_2fmode_5ftype_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fsystem_5fproto_2fdiagnose_5fproto_2fmode_5ftype_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace system_proto {
namespace diagnose_proto {

enum ModeType : int {
  INVALID_MODE = 0,
  POWERON_MODE = 1,
  WORKING_MODE = 2,
  TELEOPERATION_MODE = 3,
  DEPLOYMENT_MODE = 4,
  SLEEPING_MODE = 5,
  OTA_MODE = 6,
  ABNORMAL_MODE = 7,
  CHARGING_MODE = 8,
  FACTORY_MODE = 9,
  NAVIGATION_MODE = 10,
  DATA_COLLECTION_MODE = 11,
  ModeType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ModeType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ModeType_IsValid(int value);
constexpr ModeType ModeType_MIN = INVALID_MODE;
constexpr ModeType ModeType_MAX = DATA_COLLECTION_MODE;
constexpr int ModeType_ARRAYSIZE = ModeType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ModeType_descriptor();
template<typename T>
inline const std::string& ModeType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ModeType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ModeType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ModeType_descriptor(), enum_t_value);
}
inline bool ModeType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ModeType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ModeType>(
    ModeType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace diagnose_proto
}  // namespace system_proto
}  // namespace galbot

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::galbot::system_proto::diagnose_proto::ModeType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::galbot::system_proto::diagnose_proto::ModeType>() {
  return ::galbot::system_proto::diagnose_proto::ModeType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fsystem_5fproto_2fdiagnose_5fproto_2fmode_5ftype_2eproto
