// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/system_proto/record_proto/record_cmd.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto;
namespace galbot {
namespace record {
namespace proto {
class RecordCommand;
class RecordCommandDefaultTypeInternal;
extern RecordCommandDefaultTypeInternal _RecordCommand_default_instance_;
class RecordError;
class RecordErrorDefaultTypeInternal;
extern RecordErrorDefaultTypeInternal _RecordError_default_instance_;
class StartRecordParam;
class StartRecordParamDefaultTypeInternal;
extern StartRecordParamDefaultTypeInternal _StartRecordParam_default_instance_;
}  // namespace proto
}  // namespace record
}  // namespace galbot
PROTOBUF_NAMESPACE_OPEN
template<> ::galbot::record::proto::RecordCommand* Arena::CreateMaybeMessage<::galbot::record::proto::RecordCommand>(Arena*);
template<> ::galbot::record::proto::RecordError* Arena::CreateMaybeMessage<::galbot::record::proto::RecordError>(Arena*);
template<> ::galbot::record::proto::StartRecordParam* Arena::CreateMaybeMessage<::galbot::record::proto::StartRecordParam>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace record {
namespace proto {

enum RecordCommandType : int {
  CommandType_Unknown = 0,
  CommandType_StartRecord = 1,
  CommandType_StopRecord = 2,
  CommandType_CancelRecord = 3,
  CommandType_ConfirmRecord = 4,
  CommandType_ActionFailed = 5,
  RecordCommandType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  RecordCommandType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool RecordCommandType_IsValid(int value);
constexpr RecordCommandType RecordCommandType_MIN = CommandType_Unknown;
constexpr RecordCommandType RecordCommandType_MAX = CommandType_ActionFailed;
constexpr int RecordCommandType_ARRAYSIZE = RecordCommandType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RecordCommandType_descriptor();
template<typename T>
inline const std::string& RecordCommandType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RecordCommandType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RecordCommandType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RecordCommandType_descriptor(), enum_t_value);
}
inline bool RecordCommandType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RecordCommandType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RecordCommandType>(
    RecordCommandType_descriptor(), name, value);
}
enum RecordErrorCode : int {
  ErrorCode_Unknown = 0,
  ErrorCode_InvalidState = 1,
  ErrorCode_InternalError = 2,
  RecordErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  RecordErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool RecordErrorCode_IsValid(int value);
constexpr RecordErrorCode RecordErrorCode_MIN = ErrorCode_Unknown;
constexpr RecordErrorCode RecordErrorCode_MAX = ErrorCode_InternalError;
constexpr int RecordErrorCode_ARRAYSIZE = RecordErrorCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RecordErrorCode_descriptor();
template<typename T>
inline const std::string& RecordErrorCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RecordErrorCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RecordErrorCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RecordErrorCode_descriptor(), enum_t_value);
}
inline bool RecordErrorCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RecordErrorCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RecordErrorCode>(
    RecordErrorCode_descriptor(), name, value);
}
// ===================================================================

class StartRecordParam PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.record.proto.StartRecordParam) */ {
 public:
  inline StartRecordParam() : StartRecordParam(nullptr) {}
  virtual ~StartRecordParam();

  StartRecordParam(const StartRecordParam& from);
  StartRecordParam(StartRecordParam&& from) noexcept
    : StartRecordParam() {
    *this = ::std::move(from);
  }

  inline StartRecordParam& operator=(const StartRecordParam& from) {
    CopyFrom(from);
    return *this;
  }
  inline StartRecordParam& operator=(StartRecordParam&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StartRecordParam& default_instance();

  static inline const StartRecordParam* internal_default_instance() {
    return reinterpret_cast<const StartRecordParam*>(
               &_StartRecordParam_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(StartRecordParam& a, StartRecordParam& b) {
    a.Swap(&b);
  }
  inline void Swap(StartRecordParam* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StartRecordParam* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StartRecordParam* New() const final {
    return CreateMaybeMessage<StartRecordParam>(nullptr);
  }

  StartRecordParam* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StartRecordParam>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StartRecordParam& from);
  void MergeFrom(const StartRecordParam& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StartRecordParam* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.record.proto.StartRecordParam";
  }
  protected:
  explicit StartRecordParam(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto);
    return ::descriptor_table_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSubSaveDirFieldNumber = 1,
  };
  // string sub_save_dir = 1;
  void clear_sub_save_dir();
  const std::string& sub_save_dir() const;
  void set_sub_save_dir(const std::string& value);
  void set_sub_save_dir(std::string&& value);
  void set_sub_save_dir(const char* value);
  void set_sub_save_dir(const char* value, size_t size);
  std::string* mutable_sub_save_dir();
  std::string* release_sub_save_dir();
  void set_allocated_sub_save_dir(std::string* sub_save_dir);
  private:
  const std::string& _internal_sub_save_dir() const;
  void _internal_set_sub_save_dir(const std::string& value);
  std::string* _internal_mutable_sub_save_dir();
  public:

  // @@protoc_insertion_point(class_scope:galbot.record.proto.StartRecordParam)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sub_save_dir_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto;
};
// -------------------------------------------------------------------

class RecordCommand PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.record.proto.RecordCommand) */ {
 public:
  inline RecordCommand() : RecordCommand(nullptr) {}
  virtual ~RecordCommand();

  RecordCommand(const RecordCommand& from);
  RecordCommand(RecordCommand&& from) noexcept
    : RecordCommand() {
    *this = ::std::move(from);
  }

  inline RecordCommand& operator=(const RecordCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecordCommand& operator=(RecordCommand&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RecordCommand& default_instance();

  enum ParamCase {
    kStartRecordParam = 10,
    PARAM_NOT_SET = 0,
  };

  static inline const RecordCommand* internal_default_instance() {
    return reinterpret_cast<const RecordCommand*>(
               &_RecordCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RecordCommand& a, RecordCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(RecordCommand* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecordCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RecordCommand* New() const final {
    return CreateMaybeMessage<RecordCommand>(nullptr);
  }

  RecordCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RecordCommand>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RecordCommand& from);
  void MergeFrom(const RecordCommand& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RecordCommand* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.record.proto.RecordCommand";
  }
  protected:
  explicit RecordCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto);
    return ::descriptor_table_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kStartRecordParamFieldNumber = 10,
  };
  // .galbot.record.proto.RecordCommandType type = 1;
  void clear_type();
  ::galbot::record::proto::RecordCommandType type() const;
  void set_type(::galbot::record::proto::RecordCommandType value);
  private:
  ::galbot::record::proto::RecordCommandType _internal_type() const;
  void _internal_set_type(::galbot::record::proto::RecordCommandType value);
  public:

  // .galbot.record.proto.StartRecordParam start_record_param = 10;
  bool has_start_record_param() const;
  private:
  bool _internal_has_start_record_param() const;
  public:
  void clear_start_record_param();
  const ::galbot::record::proto::StartRecordParam& start_record_param() const;
  ::galbot::record::proto::StartRecordParam* release_start_record_param();
  ::galbot::record::proto::StartRecordParam* mutable_start_record_param();
  void set_allocated_start_record_param(::galbot::record::proto::StartRecordParam* start_record_param);
  private:
  const ::galbot::record::proto::StartRecordParam& _internal_start_record_param() const;
  ::galbot::record::proto::StartRecordParam* _internal_mutable_start_record_param();
  public:
  void unsafe_arena_set_allocated_start_record_param(
      ::galbot::record::proto::StartRecordParam* start_record_param);
  ::galbot::record::proto::StartRecordParam* unsafe_arena_release_start_record_param();

  void clear_param();
  ParamCase param_case() const;
  // @@protoc_insertion_point(class_scope:galbot.record.proto.RecordCommand)
 private:
  class _Internal;
  void set_has_start_record_param();

  inline bool has_param() const;
  inline void clear_has_param();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int type_;
  union ParamUnion {
    ParamUnion() {}
    ::galbot::record::proto::StartRecordParam* start_record_param_;
  } param_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto;
};
// -------------------------------------------------------------------

class RecordError PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.record.proto.RecordError) */ {
 public:
  inline RecordError() : RecordError(nullptr) {}
  virtual ~RecordError();

  RecordError(const RecordError& from);
  RecordError(RecordError&& from) noexcept
    : RecordError() {
    *this = ::std::move(from);
  }

  inline RecordError& operator=(const RecordError& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecordError& operator=(RecordError&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RecordError& default_instance();

  static inline const RecordError* internal_default_instance() {
    return reinterpret_cast<const RecordError*>(
               &_RecordError_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RecordError& a, RecordError& b) {
    a.Swap(&b);
  }
  inline void Swap(RecordError* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecordError* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RecordError* New() const final {
    return CreateMaybeMessage<RecordError>(nullptr);
  }

  RecordError* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RecordError>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RecordError& from);
  void MergeFrom(const RecordError& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RecordError* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.record.proto.RecordError";
  }
  protected:
  explicit RecordError(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto);
    return ::descriptor_table_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // string msg = 2;
  void clear_msg();
  const std::string& msg() const;
  void set_msg(const std::string& value);
  void set_msg(std::string&& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  std::string* mutable_msg();
  std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // .galbot.record.proto.RecordErrorCode code = 1;
  void clear_code();
  ::galbot::record::proto::RecordErrorCode code() const;
  void set_code(::galbot::record::proto::RecordErrorCode value);
  private:
  ::galbot::record::proto::RecordErrorCode _internal_code() const;
  void _internal_set_code(::galbot::record::proto::RecordErrorCode value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.record.proto.RecordError)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
  int code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StartRecordParam

// string sub_save_dir = 1;
inline void StartRecordParam::clear_sub_save_dir() {
  sub_save_dir_.ClearToEmpty();
}
inline const std::string& StartRecordParam::sub_save_dir() const {
  // @@protoc_insertion_point(field_get:galbot.record.proto.StartRecordParam.sub_save_dir)
  return _internal_sub_save_dir();
}
inline void StartRecordParam::set_sub_save_dir(const std::string& value) {
  _internal_set_sub_save_dir(value);
  // @@protoc_insertion_point(field_set:galbot.record.proto.StartRecordParam.sub_save_dir)
}
inline std::string* StartRecordParam::mutable_sub_save_dir() {
  // @@protoc_insertion_point(field_mutable:galbot.record.proto.StartRecordParam.sub_save_dir)
  return _internal_mutable_sub_save_dir();
}
inline const std::string& StartRecordParam::_internal_sub_save_dir() const {
  return sub_save_dir_.Get();
}
inline void StartRecordParam::_internal_set_sub_save_dir(const std::string& value) {
  
  sub_save_dir_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void StartRecordParam::set_sub_save_dir(std::string&& value) {
  
  sub_save_dir_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.record.proto.StartRecordParam.sub_save_dir)
}
inline void StartRecordParam::set_sub_save_dir(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sub_save_dir_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.record.proto.StartRecordParam.sub_save_dir)
}
inline void StartRecordParam::set_sub_save_dir(const char* value,
    size_t size) {
  
  sub_save_dir_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.record.proto.StartRecordParam.sub_save_dir)
}
inline std::string* StartRecordParam::_internal_mutable_sub_save_dir() {
  
  return sub_save_dir_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* StartRecordParam::release_sub_save_dir() {
  // @@protoc_insertion_point(field_release:galbot.record.proto.StartRecordParam.sub_save_dir)
  return sub_save_dir_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void StartRecordParam::set_allocated_sub_save_dir(std::string* sub_save_dir) {
  if (sub_save_dir != nullptr) {
    
  } else {
    
  }
  sub_save_dir_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sub_save_dir,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.record.proto.StartRecordParam.sub_save_dir)
}

// -------------------------------------------------------------------

// RecordCommand

// .galbot.record.proto.RecordCommandType type = 1;
inline void RecordCommand::clear_type() {
  type_ = 0;
}
inline ::galbot::record::proto::RecordCommandType RecordCommand::_internal_type() const {
  return static_cast< ::galbot::record::proto::RecordCommandType >(type_);
}
inline ::galbot::record::proto::RecordCommandType RecordCommand::type() const {
  // @@protoc_insertion_point(field_get:galbot.record.proto.RecordCommand.type)
  return _internal_type();
}
inline void RecordCommand::_internal_set_type(::galbot::record::proto::RecordCommandType value) {
  
  type_ = value;
}
inline void RecordCommand::set_type(::galbot::record::proto::RecordCommandType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:galbot.record.proto.RecordCommand.type)
}

// .galbot.record.proto.StartRecordParam start_record_param = 10;
inline bool RecordCommand::_internal_has_start_record_param() const {
  return param_case() == kStartRecordParam;
}
inline bool RecordCommand::has_start_record_param() const {
  return _internal_has_start_record_param();
}
inline void RecordCommand::set_has_start_record_param() {
  _oneof_case_[0] = kStartRecordParam;
}
inline void RecordCommand::clear_start_record_param() {
  if (_internal_has_start_record_param()) {
    if (GetArena() == nullptr) {
      delete param_.start_record_param_;
    }
    clear_has_param();
  }
}
inline ::galbot::record::proto::StartRecordParam* RecordCommand::release_start_record_param() {
  // @@protoc_insertion_point(field_release:galbot.record.proto.RecordCommand.start_record_param)
  if (_internal_has_start_record_param()) {
    clear_has_param();
      ::galbot::record::proto::StartRecordParam* temp = param_.start_record_param_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    param_.start_record_param_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::galbot::record::proto::StartRecordParam& RecordCommand::_internal_start_record_param() const {
  return _internal_has_start_record_param()
      ? *param_.start_record_param_
      : reinterpret_cast< ::galbot::record::proto::StartRecordParam&>(::galbot::record::proto::_StartRecordParam_default_instance_);
}
inline const ::galbot::record::proto::StartRecordParam& RecordCommand::start_record_param() const {
  // @@protoc_insertion_point(field_get:galbot.record.proto.RecordCommand.start_record_param)
  return _internal_start_record_param();
}
inline ::galbot::record::proto::StartRecordParam* RecordCommand::unsafe_arena_release_start_record_param() {
  // @@protoc_insertion_point(field_unsafe_arena_release:galbot.record.proto.RecordCommand.start_record_param)
  if (_internal_has_start_record_param()) {
    clear_has_param();
    ::galbot::record::proto::StartRecordParam* temp = param_.start_record_param_;
    param_.start_record_param_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RecordCommand::unsafe_arena_set_allocated_start_record_param(::galbot::record::proto::StartRecordParam* start_record_param) {
  clear_param();
  if (start_record_param) {
    set_has_start_record_param();
    param_.start_record_param_ = start_record_param;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.record.proto.RecordCommand.start_record_param)
}
inline ::galbot::record::proto::StartRecordParam* RecordCommand::_internal_mutable_start_record_param() {
  if (!_internal_has_start_record_param()) {
    clear_param();
    set_has_start_record_param();
    param_.start_record_param_ = CreateMaybeMessage< ::galbot::record::proto::StartRecordParam >(GetArena());
  }
  return param_.start_record_param_;
}
inline ::galbot::record::proto::StartRecordParam* RecordCommand::mutable_start_record_param() {
  // @@protoc_insertion_point(field_mutable:galbot.record.proto.RecordCommand.start_record_param)
  return _internal_mutable_start_record_param();
}

inline bool RecordCommand::has_param() const {
  return param_case() != PARAM_NOT_SET;
}
inline void RecordCommand::clear_has_param() {
  _oneof_case_[0] = PARAM_NOT_SET;
}
inline RecordCommand::ParamCase RecordCommand::param_case() const {
  return RecordCommand::ParamCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// RecordError

// .galbot.record.proto.RecordErrorCode code = 1;
inline void RecordError::clear_code() {
  code_ = 0;
}
inline ::galbot::record::proto::RecordErrorCode RecordError::_internal_code() const {
  return static_cast< ::galbot::record::proto::RecordErrorCode >(code_);
}
inline ::galbot::record::proto::RecordErrorCode RecordError::code() const {
  // @@protoc_insertion_point(field_get:galbot.record.proto.RecordError.code)
  return _internal_code();
}
inline void RecordError::_internal_set_code(::galbot::record::proto::RecordErrorCode value) {
  
  code_ = value;
}
inline void RecordError::set_code(::galbot::record::proto::RecordErrorCode value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:galbot.record.proto.RecordError.code)
}

// string msg = 2;
inline void RecordError::clear_msg() {
  msg_.ClearToEmpty();
}
inline const std::string& RecordError::msg() const {
  // @@protoc_insertion_point(field_get:galbot.record.proto.RecordError.msg)
  return _internal_msg();
}
inline void RecordError::set_msg(const std::string& value) {
  _internal_set_msg(value);
  // @@protoc_insertion_point(field_set:galbot.record.proto.RecordError.msg)
}
inline std::string* RecordError::mutable_msg() {
  // @@protoc_insertion_point(field_mutable:galbot.record.proto.RecordError.msg)
  return _internal_mutable_msg();
}
inline const std::string& RecordError::_internal_msg() const {
  return msg_.Get();
}
inline void RecordError::_internal_set_msg(const std::string& value) {
  
  msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void RecordError::set_msg(std::string&& value) {
  
  msg_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.record.proto.RecordError.msg)
}
inline void RecordError::set_msg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.record.proto.RecordError.msg)
}
inline void RecordError::set_msg(const char* value,
    size_t size) {
  
  msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.record.proto.RecordError.msg)
}
inline std::string* RecordError::_internal_mutable_msg() {
  
  return msg_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* RecordError::release_msg() {
  // @@protoc_insertion_point(field_release:galbot.record.proto.RecordError.msg)
  return msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RecordError::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.record.proto.RecordError.msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace record
}  // namespace galbot

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::galbot::record::proto::RecordCommandType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::galbot::record::proto::RecordCommandType>() {
  return ::galbot::record::proto::RecordCommandType_descriptor();
}
template <> struct is_proto_enum< ::galbot::record::proto::RecordErrorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::galbot::record::proto::RecordErrorCode>() {
  return ::galbot::record::proto::RecordErrorCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fsystem_5fproto_2frecord_5fproto_2frecord_5fcmd_2eproto
