"""External dependency contracts for the photo agent."""

from __future__ import annotations

from typing import Any, Protocol

from app.photo_agent.models import CaptureResult, DeliveryResult, QualityResult, WakeSignal


class WakeDetector(Protocol):
    async def poll(self) -> WakeSignal: ...


class CameraAdapter(Protocol):
    async def get_frame(self) -> Any: ...

    async def capture(self, mode: str = "photo") -> CaptureResult: ...

    async def close(self) -> None: ...


class QualityChecker(Protocol):
    def check(self, image: Any) -> QualityResult: ...


class DeliveryAdapter(Protocol):
    def register_photo(self, photo_id: str, path: Any) -> None: ...

    async def show(self, photo_id: str) -> bool: ...

    async def deliver(self, photo_id: str) -> DeliveryResult: ...


class OmniClient(Protocol):
    async def connect(self) -> str: ...

    async def configure(self) -> None: ...

    async def prime_audio(self) -> None: ...

    async def append_audio(self, pcm: bytes) -> None: ...

    async def append_image(self, frame: Any) -> None: ...

    async def commit_input(self) -> None: ...

    async def inject_context(self, text: str) -> None: ...

    async def create_response(self, instructions: str) -> None: ...

    async def wait_response_done(self, timeout: float) -> None: ...

    async def cancel_response(self) -> None: ...

    async def submit_tool_result(self, call_id: str, output: dict[str, Any]) -> None: ...

    async def end_session(self, reason: str) -> None: ...

    async def close(self) -> None: ...
