// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/singorix_proto/singorix_error.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fsingorix_5fproto_2fsingorix_5ferror_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fsingorix_5fproto_2fsingorix_5ferror_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "galbot/core_proto/header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fsingorix_5fproto_2fsingorix_5ferror_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5ferror_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5ferror_2eproto;
namespace galbot {
namespace singorix_proto {
class ErrorDetail;
class ErrorDetailDefaultTypeInternal;
extern ErrorDetailDefaultTypeInternal _ErrorDetail_default_instance_;
class SingoriXError;
class SingoriXErrorDefaultTypeInternal;
extern SingoriXErrorDefaultTypeInternal _SingoriXError_default_instance_;
class SingoriXError_ErrorMapEntry_DoNotUse;
class SingoriXError_ErrorMapEntry_DoNotUseDefaultTypeInternal;
extern SingoriXError_ErrorMapEntry_DoNotUseDefaultTypeInternal _SingoriXError_ErrorMapEntry_DoNotUse_default_instance_;
}  // namespace singorix_proto
}  // namespace galbot
PROTOBUF_NAMESPACE_OPEN
template<> ::galbot::singorix_proto::ErrorDetail* Arena::CreateMaybeMessage<::galbot::singorix_proto::ErrorDetail>(Arena*);
template<> ::galbot::singorix_proto::SingoriXError* Arena::CreateMaybeMessage<::galbot::singorix_proto::SingoriXError>(Arena*);
template<> ::galbot::singorix_proto::SingoriXError_ErrorMapEntry_DoNotUse* Arena::CreateMaybeMessage<::galbot::singorix_proto::SingoriXError_ErrorMapEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace singorix_proto {

// ===================================================================

class ErrorDetail PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.singorix_proto.ErrorDetail) */ {
 public:
  inline ErrorDetail() : ErrorDetail(nullptr) {}
  virtual ~ErrorDetail();

  ErrorDetail(const ErrorDetail& from);
  ErrorDetail(ErrorDetail&& from) noexcept
    : ErrorDetail() {
    *this = ::std::move(from);
  }

  inline ErrorDetail& operator=(const ErrorDetail& from) {
    CopyFrom(from);
    return *this;
  }
  inline ErrorDetail& operator=(ErrorDetail&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ErrorDetail& default_instance();

  static inline const ErrorDetail* internal_default_instance() {
    return reinterpret_cast<const ErrorDetail*>(
               &_ErrorDetail_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ErrorDetail& a, ErrorDetail& b) {
    a.Swap(&b);
  }
  inline void Swap(ErrorDetail* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ErrorDetail* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ErrorDetail* New() const final {
    return CreateMaybeMessage<ErrorDetail>(nullptr);
  }

  ErrorDetail* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ErrorDetail>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ErrorDetail& from);
  void MergeFrom(const ErrorDetail& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ErrorDetail* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.singorix_proto.ErrorDetail";
  }
  protected:
  explicit ErrorDetail(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5ferror_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5ferror_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDescriptionFieldNumber = 2,
    kErrorCodeFieldNumber = 1,
  };
  // string description = 2;
  void clear_description();
  const std::string& description() const;
  void set_description(const std::string& value);
  void set_description(std::string&& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  std::string* mutable_description();
  std::string* release_description();
  void set_allocated_description(std::string* description);
  private:
  const std::string& _internal_description() const;
  void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // int32 error_code = 1;
  void clear_error_code();
  ::PROTOBUF_NAMESPACE_ID::int32 error_code() const;
  void set_error_code(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_error_code() const;
  void _internal_set_error_code(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.singorix_proto.ErrorDetail)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
  ::PROTOBUF_NAMESPACE_ID::int32 error_code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5ferror_2eproto;
};
// -------------------------------------------------------------------

class SingoriXError_ErrorMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<SingoriXError_ErrorMapEntry_DoNotUse, 
    std::string, ::galbot::singorix_proto::ErrorDetail,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<SingoriXError_ErrorMapEntry_DoNotUse, 
    std::string, ::galbot::singorix_proto::ErrorDetail,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  SingoriXError_ErrorMapEntry_DoNotUse();
  explicit SingoriXError_ErrorMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const SingoriXError_ErrorMapEntry_DoNotUse& other);
  static const SingoriXError_ErrorMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SingoriXError_ErrorMapEntry_DoNotUse*>(&_SingoriXError_ErrorMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "galbot.singorix_proto.SingoriXError.ErrorMapEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5ferror_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5ferror_2eproto.file_level_metadata[1];
  }

  public:
};

// -------------------------------------------------------------------

class SingoriXError PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.singorix_proto.SingoriXError) */ {
 public:
  inline SingoriXError() : SingoriXError(nullptr) {}
  virtual ~SingoriXError();

  SingoriXError(const SingoriXError& from);
  SingoriXError(SingoriXError&& from) noexcept
    : SingoriXError() {
    *this = ::std::move(from);
  }

  inline SingoriXError& operator=(const SingoriXError& from) {
    CopyFrom(from);
    return *this;
  }
  inline SingoriXError& operator=(SingoriXError&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SingoriXError& default_instance();

  static inline const SingoriXError* internal_default_instance() {
    return reinterpret_cast<const SingoriXError*>(
               &_SingoriXError_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SingoriXError& a, SingoriXError& b) {
    a.Swap(&b);
  }
  inline void Swap(SingoriXError* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SingoriXError* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SingoriXError* New() const final {
    return CreateMaybeMessage<SingoriXError>(nullptr);
  }

  SingoriXError* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SingoriXError>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SingoriXError& from);
  void MergeFrom(const SingoriXError& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SingoriXError* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.singorix_proto.SingoriXError";
  }
  protected:
  explicit SingoriXError(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5ferror_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5ferror_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kErrorMapFieldNumber = 2,
    kHeaderFieldNumber = 1,
  };
  // map<string, .galbot.singorix_proto.ErrorDetail> error_map = 2;
  int error_map_size() const;
  private:
  int _internal_error_map_size() const;
  public:
  void clear_error_map();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::ErrorDetail >&
      _internal_error_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::ErrorDetail >*
      _internal_mutable_error_map();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::ErrorDetail >&
      error_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::ErrorDetail >*
      mutable_error_map();

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:galbot.singorix_proto.SingoriXError)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      SingoriXError_ErrorMapEntry_DoNotUse,
      std::string, ::galbot::singorix_proto::ErrorDetail,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> error_map_;
  ::galbot::core_proto::Header* header_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5ferror_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ErrorDetail

// int32 error_code = 1;
inline void ErrorDetail::clear_error_code() {
  error_code_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ErrorDetail::_internal_error_code() const {
  return error_code_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ErrorDetail::error_code() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.ErrorDetail.error_code)
  return _internal_error_code();
}
inline void ErrorDetail::_internal_set_error_code(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  error_code_ = value;
}
inline void ErrorDetail::set_error_code(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_error_code(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.ErrorDetail.error_code)
}

// string description = 2;
inline void ErrorDetail::clear_description() {
  description_.ClearToEmpty();
}
inline const std::string& ErrorDetail::description() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.ErrorDetail.description)
  return _internal_description();
}
inline void ErrorDetail::set_description(const std::string& value) {
  _internal_set_description(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.ErrorDetail.description)
}
inline std::string* ErrorDetail::mutable_description() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.ErrorDetail.description)
  return _internal_mutable_description();
}
inline const std::string& ErrorDetail::_internal_description() const {
  return description_.Get();
}
inline void ErrorDetail::_internal_set_description(const std::string& value) {
  
  description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ErrorDetail::set_description(std::string&& value) {
  
  description_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.ErrorDetail.description)
}
inline void ErrorDetail::set_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.ErrorDetail.description)
}
inline void ErrorDetail::set_description(const char* value,
    size_t size) {
  
  description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.ErrorDetail.description)
}
inline std::string* ErrorDetail::_internal_mutable_description() {
  
  return description_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ErrorDetail::release_description() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.ErrorDetail.description)
  return description_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ErrorDetail::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  description_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), description,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.ErrorDetail.description)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// SingoriXError

// .galbot.core_proto.Header header = 1;
inline bool SingoriXError::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool SingoriXError::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& SingoriXError::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& SingoriXError::header() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.SingoriXError.header)
  return _internal_header();
}
inline void SingoriXError::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.singorix_proto.SingoriXError.header)
}
inline ::galbot::core_proto::Header* SingoriXError::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* SingoriXError::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.SingoriXError.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* SingoriXError::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* SingoriXError::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.SingoriXError.header)
  return _internal_mutable_header();
}
inline void SingoriXError::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.SingoriXError.header)
}

// map<string, .galbot.singorix_proto.ErrorDetail> error_map = 2;
inline int SingoriXError::_internal_error_map_size() const {
  return error_map_.size();
}
inline int SingoriXError::error_map_size() const {
  return _internal_error_map_size();
}
inline void SingoriXError::clear_error_map() {
  error_map_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::ErrorDetail >&
SingoriXError::_internal_error_map() const {
  return error_map_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::ErrorDetail >&
SingoriXError::error_map() const {
  // @@protoc_insertion_point(field_map:galbot.singorix_proto.SingoriXError.error_map)
  return _internal_error_map();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::ErrorDetail >*
SingoriXError::_internal_mutable_error_map() {
  return error_map_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::ErrorDetail >*
SingoriXError::mutable_error_map() {
  // @@protoc_insertion_point(field_mutable_map:galbot.singorix_proto.SingoriXError.error_map)
  return _internal_mutable_error_map();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace singorix_proto
}  // namespace galbot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fsingorix_5fproto_2fsingorix_5ferror_2eproto
