// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/perception_proto/perception_esdf.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fperception_5fproto_2fperception_5fesdf_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fperception_5fproto_2fperception_5fesdf_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "galbot/spatial_proto/pose.pb.h"
#include "galbot/core_proto/math.pb.h"
#include "galbot/core_proto/header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fperception_5fproto_2fperception_5fesdf_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fperception_5fproto_2fperception_5fesdf_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fperception_5fproto_2fperception_5fesdf_2eproto;
namespace galbot {
namespace perception_proto {
class EsdfGrid;
class EsdfGridDefaultTypeInternal;
extern EsdfGridDefaultTypeInternal _EsdfGrid_default_instance_;
}  // namespace perception_proto
}  // namespace galbot
PROTOBUF_NAMESPACE_OPEN
template<> ::galbot::perception_proto::EsdfGrid* Arena::CreateMaybeMessage<::galbot::perception_proto::EsdfGrid>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace perception_proto {

// ===================================================================

class EsdfGrid PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.perception_proto.EsdfGrid) */ {
 public:
  inline EsdfGrid() : EsdfGrid(nullptr) {}
  virtual ~EsdfGrid();

  EsdfGrid(const EsdfGrid& from);
  EsdfGrid(EsdfGrid&& from) noexcept
    : EsdfGrid() {
    *this = ::std::move(from);
  }

  inline EsdfGrid& operator=(const EsdfGrid& from) {
    CopyFrom(from);
    return *this;
  }
  inline EsdfGrid& operator=(EsdfGrid&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EsdfGrid& default_instance();

  static inline const EsdfGrid* internal_default_instance() {
    return reinterpret_cast<const EsdfGrid*>(
               &_EsdfGrid_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EsdfGrid& a, EsdfGrid& b) {
    a.Swap(&b);
  }
  inline void Swap(EsdfGrid* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EsdfGrid* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EsdfGrid* New() const final {
    return CreateMaybeMessage<EsdfGrid>(nullptr);
  }

  EsdfGrid* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EsdfGrid>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EsdfGrid& from);
  void MergeFrom(const EsdfGrid& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EsdfGrid* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.perception_proto.EsdfGrid";
  }
  protected:
  explicit EsdfGrid(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fperception_5fproto_2fperception_5fesdf_2eproto);
    return ::descriptor_table_galbot_2fperception_5fproto_2fperception_5fesdf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVoxelDistancesFieldNumber = 7,
    kHeaderFieldNumber = 1,
    kOriginPointFieldNumber = 6,
    kCurrentPoseFieldNumber = 8,
    kVoxelSizeMFieldNumber = 2,
    kVoxelCountXFieldNumber = 3,
    kVoxelCountYFieldNumber = 4,
    kVoxelCountZFieldNumber = 5,
  };
  // repeated float voxel_distances = 7;
  int voxel_distances_size() const;
  private:
  int _internal_voxel_distances_size() const;
  public:
  void clear_voxel_distances();
  private:
  float _internal_voxel_distances(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_voxel_distances() const;
  void _internal_add_voxel_distances(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_voxel_distances();
  public:
  float voxel_distances(int index) const;
  void set_voxel_distances(int index, float value);
  void add_voxel_distances(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      voxel_distances() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_voxel_distances();

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // .galbot.core_proto.Point origin_point = 6;
  bool has_origin_point() const;
  private:
  bool _internal_has_origin_point() const;
  public:
  void clear_origin_point();
  const ::galbot::core_proto::Point& origin_point() const;
  ::galbot::core_proto::Point* release_origin_point();
  ::galbot::core_proto::Point* mutable_origin_point();
  void set_allocated_origin_point(::galbot::core_proto::Point* origin_point);
  private:
  const ::galbot::core_proto::Point& _internal_origin_point() const;
  ::galbot::core_proto::Point* _internal_mutable_origin_point();
  public:
  void unsafe_arena_set_allocated_origin_point(
      ::galbot::core_proto::Point* origin_point);
  ::galbot::core_proto::Point* unsafe_arena_release_origin_point();

  // .galbot.spatial_proto.PoseMsg current_pose = 8;
  bool has_current_pose() const;
  private:
  bool _internal_has_current_pose() const;
  public:
  void clear_current_pose();
  const ::galbot::spatial_proto::PoseMsg& current_pose() const;
  ::galbot::spatial_proto::PoseMsg* release_current_pose();
  ::galbot::spatial_proto::PoseMsg* mutable_current_pose();
  void set_allocated_current_pose(::galbot::spatial_proto::PoseMsg* current_pose);
  private:
  const ::galbot::spatial_proto::PoseMsg& _internal_current_pose() const;
  ::galbot::spatial_proto::PoseMsg* _internal_mutable_current_pose();
  public:
  void unsafe_arena_set_allocated_current_pose(
      ::galbot::spatial_proto::PoseMsg* current_pose);
  ::galbot::spatial_proto::PoseMsg* unsafe_arena_release_current_pose();

  // float voxel_size_m = 2;
  void clear_voxel_size_m();
  float voxel_size_m() const;
  void set_voxel_size_m(float value);
  private:
  float _internal_voxel_size_m() const;
  void _internal_set_voxel_size_m(float value);
  public:

  // uint32 voxel_count_x = 3;
  void clear_voxel_count_x();
  ::PROTOBUF_NAMESPACE_ID::uint32 voxel_count_x() const;
  void set_voxel_count_x(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_voxel_count_x() const;
  void _internal_set_voxel_count_x(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 voxel_count_y = 4;
  void clear_voxel_count_y();
  ::PROTOBUF_NAMESPACE_ID::uint32 voxel_count_y() const;
  void set_voxel_count_y(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_voxel_count_y() const;
  void _internal_set_voxel_count_y(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 voxel_count_z = 5;
  void clear_voxel_count_z();
  ::PROTOBUF_NAMESPACE_ID::uint32 voxel_count_z() const;
  void set_voxel_count_z(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_voxel_count_z() const;
  void _internal_set_voxel_count_z(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.perception_proto.EsdfGrid)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > voxel_distances_;
  mutable std::atomic<int> _voxel_distances_cached_byte_size_;
  ::galbot::core_proto::Header* header_;
  ::galbot::core_proto::Point* origin_point_;
  ::galbot::spatial_proto::PoseMsg* current_pose_;
  float voxel_size_m_;
  ::PROTOBUF_NAMESPACE_ID::uint32 voxel_count_x_;
  ::PROTOBUF_NAMESPACE_ID::uint32 voxel_count_y_;
  ::PROTOBUF_NAMESPACE_ID::uint32 voxel_count_z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fperception_5fproto_2fperception_5fesdf_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EsdfGrid

// .galbot.core_proto.Header header = 1;
inline bool EsdfGrid::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool EsdfGrid::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& EsdfGrid::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& EsdfGrid::header() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.EsdfGrid.header)
  return _internal_header();
}
inline void EsdfGrid::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.perception_proto.EsdfGrid.header)
}
inline ::galbot::core_proto::Header* EsdfGrid::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* EsdfGrid::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.EsdfGrid.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* EsdfGrid::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* EsdfGrid::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.EsdfGrid.header)
  return _internal_mutable_header();
}
inline void EsdfGrid::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.EsdfGrid.header)
}

// float voxel_size_m = 2;
inline void EsdfGrid::clear_voxel_size_m() {
  voxel_size_m_ = 0;
}
inline float EsdfGrid::_internal_voxel_size_m() const {
  return voxel_size_m_;
}
inline float EsdfGrid::voxel_size_m() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.EsdfGrid.voxel_size_m)
  return _internal_voxel_size_m();
}
inline void EsdfGrid::_internal_set_voxel_size_m(float value) {
  
  voxel_size_m_ = value;
}
inline void EsdfGrid::set_voxel_size_m(float value) {
  _internal_set_voxel_size_m(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.EsdfGrid.voxel_size_m)
}

// uint32 voxel_count_x = 3;
inline void EsdfGrid::clear_voxel_count_x() {
  voxel_count_x_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 EsdfGrid::_internal_voxel_count_x() const {
  return voxel_count_x_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 EsdfGrid::voxel_count_x() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.EsdfGrid.voxel_count_x)
  return _internal_voxel_count_x();
}
inline void EsdfGrid::_internal_set_voxel_count_x(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  voxel_count_x_ = value;
}
inline void EsdfGrid::set_voxel_count_x(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_voxel_count_x(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.EsdfGrid.voxel_count_x)
}

// uint32 voxel_count_y = 4;
inline void EsdfGrid::clear_voxel_count_y() {
  voxel_count_y_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 EsdfGrid::_internal_voxel_count_y() const {
  return voxel_count_y_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 EsdfGrid::voxel_count_y() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.EsdfGrid.voxel_count_y)
  return _internal_voxel_count_y();
}
inline void EsdfGrid::_internal_set_voxel_count_y(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  voxel_count_y_ = value;
}
inline void EsdfGrid::set_voxel_count_y(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_voxel_count_y(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.EsdfGrid.voxel_count_y)
}

// uint32 voxel_count_z = 5;
inline void EsdfGrid::clear_voxel_count_z() {
  voxel_count_z_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 EsdfGrid::_internal_voxel_count_z() const {
  return voxel_count_z_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 EsdfGrid::voxel_count_z() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.EsdfGrid.voxel_count_z)
  return _internal_voxel_count_z();
}
inline void EsdfGrid::_internal_set_voxel_count_z(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  voxel_count_z_ = value;
}
inline void EsdfGrid::set_voxel_count_z(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_voxel_count_z(value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.EsdfGrid.voxel_count_z)
}

// .galbot.core_proto.Point origin_point = 6;
inline bool EsdfGrid::_internal_has_origin_point() const {
  return this != internal_default_instance() && origin_point_ != nullptr;
}
inline bool EsdfGrid::has_origin_point() const {
  return _internal_has_origin_point();
}
inline const ::galbot::core_proto::Point& EsdfGrid::_internal_origin_point() const {
  const ::galbot::core_proto::Point* p = origin_point_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Point&>(
      ::galbot::core_proto::_Point_default_instance_);
}
inline const ::galbot::core_proto::Point& EsdfGrid::origin_point() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.EsdfGrid.origin_point)
  return _internal_origin_point();
}
inline void EsdfGrid::unsafe_arena_set_allocated_origin_point(
    ::galbot::core_proto::Point* origin_point) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(origin_point_);
  }
  origin_point_ = origin_point;
  if (origin_point) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.perception_proto.EsdfGrid.origin_point)
}
inline ::galbot::core_proto::Point* EsdfGrid::release_origin_point() {
  
  ::galbot::core_proto::Point* temp = origin_point_;
  origin_point_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Point* EsdfGrid::unsafe_arena_release_origin_point() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.EsdfGrid.origin_point)
  
  ::galbot::core_proto::Point* temp = origin_point_;
  origin_point_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Point* EsdfGrid::_internal_mutable_origin_point() {
  
  if (origin_point_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Point>(GetArena());
    origin_point_ = p;
  }
  return origin_point_;
}
inline ::galbot::core_proto::Point* EsdfGrid::mutable_origin_point() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.EsdfGrid.origin_point)
  return _internal_mutable_origin_point();
}
inline void EsdfGrid::set_allocated_origin_point(::galbot::core_proto::Point* origin_point) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(origin_point_);
  }
  if (origin_point) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(origin_point)->GetArena();
    if (message_arena != submessage_arena) {
      origin_point = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, origin_point, submessage_arena);
    }
    
  } else {
    
  }
  origin_point_ = origin_point;
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.EsdfGrid.origin_point)
}

// repeated float voxel_distances = 7;
inline int EsdfGrid::_internal_voxel_distances_size() const {
  return voxel_distances_.size();
}
inline int EsdfGrid::voxel_distances_size() const {
  return _internal_voxel_distances_size();
}
inline void EsdfGrid::clear_voxel_distances() {
  voxel_distances_.Clear();
}
inline float EsdfGrid::_internal_voxel_distances(int index) const {
  return voxel_distances_.Get(index);
}
inline float EsdfGrid::voxel_distances(int index) const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.EsdfGrid.voxel_distances)
  return _internal_voxel_distances(index);
}
inline void EsdfGrid::set_voxel_distances(int index, float value) {
  voxel_distances_.Set(index, value);
  // @@protoc_insertion_point(field_set:galbot.perception_proto.EsdfGrid.voxel_distances)
}
inline void EsdfGrid::_internal_add_voxel_distances(float value) {
  voxel_distances_.Add(value);
}
inline void EsdfGrid::add_voxel_distances(float value) {
  _internal_add_voxel_distances(value);
  // @@protoc_insertion_point(field_add:galbot.perception_proto.EsdfGrid.voxel_distances)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
EsdfGrid::_internal_voxel_distances() const {
  return voxel_distances_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
EsdfGrid::voxel_distances() const {
  // @@protoc_insertion_point(field_list:galbot.perception_proto.EsdfGrid.voxel_distances)
  return _internal_voxel_distances();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
EsdfGrid::_internal_mutable_voxel_distances() {
  return &voxel_distances_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
EsdfGrid::mutable_voxel_distances() {
  // @@protoc_insertion_point(field_mutable_list:galbot.perception_proto.EsdfGrid.voxel_distances)
  return _internal_mutable_voxel_distances();
}

// .galbot.spatial_proto.PoseMsg current_pose = 8;
inline bool EsdfGrid::_internal_has_current_pose() const {
  return this != internal_default_instance() && current_pose_ != nullptr;
}
inline bool EsdfGrid::has_current_pose() const {
  return _internal_has_current_pose();
}
inline const ::galbot::spatial_proto::PoseMsg& EsdfGrid::_internal_current_pose() const {
  const ::galbot::spatial_proto::PoseMsg* p = current_pose_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::spatial_proto::PoseMsg&>(
      ::galbot::spatial_proto::_PoseMsg_default_instance_);
}
inline const ::galbot::spatial_proto::PoseMsg& EsdfGrid::current_pose() const {
  // @@protoc_insertion_point(field_get:galbot.perception_proto.EsdfGrid.current_pose)
  return _internal_current_pose();
}
inline void EsdfGrid::unsafe_arena_set_allocated_current_pose(
    ::galbot::spatial_proto::PoseMsg* current_pose) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(current_pose_);
  }
  current_pose_ = current_pose;
  if (current_pose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.perception_proto.EsdfGrid.current_pose)
}
inline ::galbot::spatial_proto::PoseMsg* EsdfGrid::release_current_pose() {
  
  ::galbot::spatial_proto::PoseMsg* temp = current_pose_;
  current_pose_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::spatial_proto::PoseMsg* EsdfGrid::unsafe_arena_release_current_pose() {
  // @@protoc_insertion_point(field_release:galbot.perception_proto.EsdfGrid.current_pose)
  
  ::galbot::spatial_proto::PoseMsg* temp = current_pose_;
  current_pose_ = nullptr;
  return temp;
}
inline ::galbot::spatial_proto::PoseMsg* EsdfGrid::_internal_mutable_current_pose() {
  
  if (current_pose_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::spatial_proto::PoseMsg>(GetArena());
    current_pose_ = p;
  }
  return current_pose_;
}
inline ::galbot::spatial_proto::PoseMsg* EsdfGrid::mutable_current_pose() {
  // @@protoc_insertion_point(field_mutable:galbot.perception_proto.EsdfGrid.current_pose)
  return _internal_mutable_current_pose();
}
inline void EsdfGrid::set_allocated_current_pose(::galbot::spatial_proto::PoseMsg* current_pose) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(current_pose_);
  }
  if (current_pose) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(current_pose)->GetArena();
    if (message_arena != submessage_arena) {
      current_pose = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, current_pose, submessage_arena);
    }
    
  } else {
    
  }
  current_pose_ = current_pose;
  // @@protoc_insertion_point(field_set_allocated:galbot.perception_proto.EsdfGrid.current_pose)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace perception_proto
}  // namespace galbot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fperception_5fproto_2fperception_5fesdf_2eproto
