// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/tf2_proto/tf2_error.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2ftf2_5fproto_2ftf2_5ferror_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2ftf2_5fproto_2ftf2_5ferror_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2ftf2_5fproto_2ftf2_5ferror_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2ftf2_5fproto_2ftf2_5ferror_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2ftf2_5fproto_2ftf2_5ferror_2eproto;
namespace galbot {
namespace tf2_proto {
class TF2Error;
class TF2ErrorDefaultTypeInternal;
extern TF2ErrorDefaultTypeInternal _TF2Error_default_instance_;
}  // namespace tf2_proto
}  // namespace galbot
PROTOBUF_NAMESPACE_OPEN
template<> ::galbot::tf2_proto::TF2Error* Arena::CreateMaybeMessage<::galbot::tf2_proto::TF2Error>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace tf2_proto {

enum ErrorType : int {
  NO_ERROR = 0,
  LOOKUP_ERROR = 1,
  CONNECTIVITY_ERROR = 2,
  EXTRAPOLATION_ERROR = 3,
  INVALID_ARGUMENT_ERROR = 4,
  TIMEOUT_ERROR = 5,
  TRANSFORM_ERROR = 6,
  ErrorType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ErrorType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ErrorType_IsValid(int value);
constexpr ErrorType ErrorType_MIN = NO_ERROR;
constexpr ErrorType ErrorType_MAX = TRANSFORM_ERROR;
constexpr int ErrorType_ARRAYSIZE = ErrorType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ErrorType_descriptor();
template<typename T>
inline const std::string& ErrorType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ErrorType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ErrorType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ErrorType_descriptor(), enum_t_value);
}
inline bool ErrorType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ErrorType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ErrorType>(
    ErrorType_descriptor(), name, value);
}
// ===================================================================

class TF2Error PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.tf2_proto.TF2Error) */ {
 public:
  inline TF2Error() : TF2Error(nullptr) {}
  virtual ~TF2Error();

  TF2Error(const TF2Error& from);
  TF2Error(TF2Error&& from) noexcept
    : TF2Error() {
    *this = ::std::move(from);
  }

  inline TF2Error& operator=(const TF2Error& from) {
    CopyFrom(from);
    return *this;
  }
  inline TF2Error& operator=(TF2Error&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TF2Error& default_instance();

  static inline const TF2Error* internal_default_instance() {
    return reinterpret_cast<const TF2Error*>(
               &_TF2Error_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TF2Error& a, TF2Error& b) {
    a.Swap(&b);
  }
  inline void Swap(TF2Error* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TF2Error* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TF2Error* New() const final {
    return CreateMaybeMessage<TF2Error>(nullptr);
  }

  TF2Error* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TF2Error>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TF2Error& from);
  void MergeFrom(const TF2Error& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TF2Error* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.tf2_proto.TF2Error";
  }
  protected:
  explicit TF2Error(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2ftf2_5fproto_2ftf2_5ferror_2eproto);
    return ::descriptor_table_galbot_2ftf2_5fproto_2ftf2_5ferror_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorStringFieldNumber = 2,
    kErrorFieldNumber = 1,
  };
  // string error_string = 2;
  void clear_error_string();
  const std::string& error_string() const;
  void set_error_string(const std::string& value);
  void set_error_string(std::string&& value);
  void set_error_string(const char* value);
  void set_error_string(const char* value, size_t size);
  std::string* mutable_error_string();
  std::string* release_error_string();
  void set_allocated_error_string(std::string* error_string);
  private:
  const std::string& _internal_error_string() const;
  void _internal_set_error_string(const std::string& value);
  std::string* _internal_mutable_error_string();
  public:

  // .galbot.tf2_proto.ErrorType error = 1;
  void clear_error();
  ::galbot::tf2_proto::ErrorType error() const;
  void set_error(::galbot::tf2_proto::ErrorType value);
  private:
  ::galbot::tf2_proto::ErrorType _internal_error() const;
  void _internal_set_error(::galbot::tf2_proto::ErrorType value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.tf2_proto.TF2Error)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_string_;
  int error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2ftf2_5fproto_2ftf2_5ferror_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TF2Error

// .galbot.tf2_proto.ErrorType error = 1;
inline void TF2Error::clear_error() {
  error_ = 0;
}
inline ::galbot::tf2_proto::ErrorType TF2Error::_internal_error() const {
  return static_cast< ::galbot::tf2_proto::ErrorType >(error_);
}
inline ::galbot::tf2_proto::ErrorType TF2Error::error() const {
  // @@protoc_insertion_point(field_get:galbot.tf2_proto.TF2Error.error)
  return _internal_error();
}
inline void TF2Error::_internal_set_error(::galbot::tf2_proto::ErrorType value) {
  
  error_ = value;
}
inline void TF2Error::set_error(::galbot::tf2_proto::ErrorType value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:galbot.tf2_proto.TF2Error.error)
}

// string error_string = 2;
inline void TF2Error::clear_error_string() {
  error_string_.ClearToEmpty();
}
inline const std::string& TF2Error::error_string() const {
  // @@protoc_insertion_point(field_get:galbot.tf2_proto.TF2Error.error_string)
  return _internal_error_string();
}
inline void TF2Error::set_error_string(const std::string& value) {
  _internal_set_error_string(value);
  // @@protoc_insertion_point(field_set:galbot.tf2_proto.TF2Error.error_string)
}
inline std::string* TF2Error::mutable_error_string() {
  // @@protoc_insertion_point(field_mutable:galbot.tf2_proto.TF2Error.error_string)
  return _internal_mutable_error_string();
}
inline const std::string& TF2Error::_internal_error_string() const {
  return error_string_.Get();
}
inline void TF2Error::_internal_set_error_string(const std::string& value) {
  
  error_string_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TF2Error::set_error_string(std::string&& value) {
  
  error_string_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.tf2_proto.TF2Error.error_string)
}
inline void TF2Error::set_error_string(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  error_string_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.tf2_proto.TF2Error.error_string)
}
inline void TF2Error::set_error_string(const char* value,
    size_t size) {
  
  error_string_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.tf2_proto.TF2Error.error_string)
}
inline std::string* TF2Error::_internal_mutable_error_string() {
  
  return error_string_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TF2Error::release_error_string() {
  // @@protoc_insertion_point(field_release:galbot.tf2_proto.TF2Error.error_string)
  return error_string_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TF2Error::set_allocated_error_string(std::string* error_string) {
  if (error_string != nullptr) {
    
  } else {
    
  }
  error_string_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error_string,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.tf2_proto.TF2Error.error_string)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace tf2_proto
}  // namespace galbot

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::galbot::tf2_proto::ErrorType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::galbot::tf2_proto::ErrorType>() {
  return ::galbot::tf2_proto::ErrorType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2ftf2_5fproto_2ftf2_5ferror_2eproto
