// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/navigation_proto/map.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fnavigation_5fproto_2fmap_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fnavigation_5fproto_2fmap_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "galbot/core_proto/time.pb.h"
#include "galbot/core_proto/header.pb.h"
#include "galbot/core_proto/math.pb.h"
#include "galbot/spatial_proto/pose.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fnavigation_5fproto_2fmap_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fnavigation_5fproto_2fmap_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fnavigation_5fproto_2fmap_2eproto;
namespace galbot {
namespace navigation_proto {
class GridCells;
class GridCellsDefaultTypeInternal;
extern GridCellsDefaultTypeInternal _GridCells_default_instance_;
class MapMetaData;
class MapMetaDataDefaultTypeInternal;
extern MapMetaDataDefaultTypeInternal _MapMetaData_default_instance_;
class OccupancyGrid;
class OccupancyGridDefaultTypeInternal;
extern OccupancyGridDefaultTypeInternal _OccupancyGrid_default_instance_;
}  // namespace navigation_proto
}  // namespace galbot
PROTOBUF_NAMESPACE_OPEN
template<> ::galbot::navigation_proto::GridCells* Arena::CreateMaybeMessage<::galbot::navigation_proto::GridCells>(Arena*);
template<> ::galbot::navigation_proto::MapMetaData* Arena::CreateMaybeMessage<::galbot::navigation_proto::MapMetaData>(Arena*);
template<> ::galbot::navigation_proto::OccupancyGrid* Arena::CreateMaybeMessage<::galbot::navigation_proto::OccupancyGrid>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace navigation_proto {

// ===================================================================

class GridCells PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.navigation_proto.GridCells) */ {
 public:
  inline GridCells() : GridCells(nullptr) {}
  virtual ~GridCells();

  GridCells(const GridCells& from);
  GridCells(GridCells&& from) noexcept
    : GridCells() {
    *this = ::std::move(from);
  }

  inline GridCells& operator=(const GridCells& from) {
    CopyFrom(from);
    return *this;
  }
  inline GridCells& operator=(GridCells&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GridCells& default_instance();

  static inline const GridCells* internal_default_instance() {
    return reinterpret_cast<const GridCells*>(
               &_GridCells_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GridCells& a, GridCells& b) {
    a.Swap(&b);
  }
  inline void Swap(GridCells* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GridCells* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GridCells* New() const final {
    return CreateMaybeMessage<GridCells>(nullptr);
  }

  GridCells* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GridCells>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GridCells& from);
  void MergeFrom(const GridCells& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GridCells* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.navigation_proto.GridCells";
  }
  protected:
  explicit GridCells(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fnavigation_5fproto_2fmap_2eproto);
    return ::descriptor_table_galbot_2fnavigation_5fproto_2fmap_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCellsFieldNumber = 4,
    kHeaderFieldNumber = 1,
    kCellWidthFieldNumber = 2,
    kCellHeightFieldNumber = 3,
  };
  // repeated .galbot.core_proto.Point cells = 4;
  int cells_size() const;
  private:
  int _internal_cells_size() const;
  public:
  void clear_cells();
  ::galbot::core_proto::Point* mutable_cells(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::galbot::core_proto::Point >*
      mutable_cells();
  private:
  const ::galbot::core_proto::Point& _internal_cells(int index) const;
  ::galbot::core_proto::Point* _internal_add_cells();
  public:
  const ::galbot::core_proto::Point& cells(int index) const;
  ::galbot::core_proto::Point* add_cells();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::galbot::core_proto::Point >&
      cells() const;

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // float cell_width = 2;
  void clear_cell_width();
  float cell_width() const;
  void set_cell_width(float value);
  private:
  float _internal_cell_width() const;
  void _internal_set_cell_width(float value);
  public:

  // float cell_height = 3;
  void clear_cell_height();
  float cell_height() const;
  void set_cell_height(float value);
  private:
  float _internal_cell_height() const;
  void _internal_set_cell_height(float value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.navigation_proto.GridCells)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::galbot::core_proto::Point > cells_;
  ::galbot::core_proto::Header* header_;
  float cell_width_;
  float cell_height_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fnavigation_5fproto_2fmap_2eproto;
};
// -------------------------------------------------------------------

class MapMetaData PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.navigation_proto.MapMetaData) */ {
 public:
  inline MapMetaData() : MapMetaData(nullptr) {}
  virtual ~MapMetaData();

  MapMetaData(const MapMetaData& from);
  MapMetaData(MapMetaData&& from) noexcept
    : MapMetaData() {
    *this = ::std::move(from);
  }

  inline MapMetaData& operator=(const MapMetaData& from) {
    CopyFrom(from);
    return *this;
  }
  inline MapMetaData& operator=(MapMetaData&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MapMetaData& default_instance();

  static inline const MapMetaData* internal_default_instance() {
    return reinterpret_cast<const MapMetaData*>(
               &_MapMetaData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MapMetaData& a, MapMetaData& b) {
    a.Swap(&b);
  }
  inline void Swap(MapMetaData* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MapMetaData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MapMetaData* New() const final {
    return CreateMaybeMessage<MapMetaData>(nullptr);
  }

  MapMetaData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MapMetaData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MapMetaData& from);
  void MergeFrom(const MapMetaData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MapMetaData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.navigation_proto.MapMetaData";
  }
  protected:
  explicit MapMetaData(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fnavigation_5fproto_2fmap_2eproto);
    return ::descriptor_table_galbot_2fnavigation_5fproto_2fmap_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMapLoadTimeFieldNumber = 1,
    kOriginFieldNumber = 5,
    kResolutionFieldNumber = 2,
    kWidthFieldNumber = 3,
    kHeightFieldNumber = 4,
  };
  // .galbot.core_proto.Timestamp map_load_time = 1;
  bool has_map_load_time() const;
  private:
  bool _internal_has_map_load_time() const;
  public:
  void clear_map_load_time();
  const ::galbot::core_proto::Timestamp& map_load_time() const;
  ::galbot::core_proto::Timestamp* release_map_load_time();
  ::galbot::core_proto::Timestamp* mutable_map_load_time();
  void set_allocated_map_load_time(::galbot::core_proto::Timestamp* map_load_time);
  private:
  const ::galbot::core_proto::Timestamp& _internal_map_load_time() const;
  ::galbot::core_proto::Timestamp* _internal_mutable_map_load_time();
  public:
  void unsafe_arena_set_allocated_map_load_time(
      ::galbot::core_proto::Timestamp* map_load_time);
  ::galbot::core_proto::Timestamp* unsafe_arena_release_map_load_time();

  // .galbot.spatial_proto.Pose origin = 5;
  bool has_origin() const;
  private:
  bool _internal_has_origin() const;
  public:
  void clear_origin();
  const ::galbot::spatial_proto::Pose& origin() const;
  ::galbot::spatial_proto::Pose* release_origin();
  ::galbot::spatial_proto::Pose* mutable_origin();
  void set_allocated_origin(::galbot::spatial_proto::Pose* origin);
  private:
  const ::galbot::spatial_proto::Pose& _internal_origin() const;
  ::galbot::spatial_proto::Pose* _internal_mutable_origin();
  public:
  void unsafe_arena_set_allocated_origin(
      ::galbot::spatial_proto::Pose* origin);
  ::galbot::spatial_proto::Pose* unsafe_arena_release_origin();

  // float resolution = 2;
  void clear_resolution();
  float resolution() const;
  void set_resolution(float value);
  private:
  float _internal_resolution() const;
  void _internal_set_resolution(float value);
  public:

  // uint32 width = 3;
  void clear_width();
  ::PROTOBUF_NAMESPACE_ID::uint32 width() const;
  void set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_width() const;
  void _internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 height = 4;
  void clear_height();
  ::PROTOBUF_NAMESPACE_ID::uint32 height() const;
  void set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_height() const;
  void _internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.navigation_proto.MapMetaData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::galbot::core_proto::Timestamp* map_load_time_;
  ::galbot::spatial_proto::Pose* origin_;
  float resolution_;
  ::PROTOBUF_NAMESPACE_ID::uint32 width_;
  ::PROTOBUF_NAMESPACE_ID::uint32 height_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fnavigation_5fproto_2fmap_2eproto;
};
// -------------------------------------------------------------------

class OccupancyGrid PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.navigation_proto.OccupancyGrid) */ {
 public:
  inline OccupancyGrid() : OccupancyGrid(nullptr) {}
  virtual ~OccupancyGrid();

  OccupancyGrid(const OccupancyGrid& from);
  OccupancyGrid(OccupancyGrid&& from) noexcept
    : OccupancyGrid() {
    *this = ::std::move(from);
  }

  inline OccupancyGrid& operator=(const OccupancyGrid& from) {
    CopyFrom(from);
    return *this;
  }
  inline OccupancyGrid& operator=(OccupancyGrid&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OccupancyGrid& default_instance();

  static inline const OccupancyGrid* internal_default_instance() {
    return reinterpret_cast<const OccupancyGrid*>(
               &_OccupancyGrid_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(OccupancyGrid& a, OccupancyGrid& b) {
    a.Swap(&b);
  }
  inline void Swap(OccupancyGrid* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OccupancyGrid* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OccupancyGrid* New() const final {
    return CreateMaybeMessage<OccupancyGrid>(nullptr);
  }

  OccupancyGrid* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OccupancyGrid>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OccupancyGrid& from);
  void MergeFrom(const OccupancyGrid& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OccupancyGrid* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.navigation_proto.OccupancyGrid";
  }
  protected:
  explicit OccupancyGrid(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fnavigation_5fproto_2fmap_2eproto);
    return ::descriptor_table_galbot_2fnavigation_5fproto_2fmap_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 3,
    kHeaderFieldNumber = 1,
    kInfoFieldNumber = 2,
  };
  // bytes data = 3;
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // .galbot.navigation_proto.MapMetaData info = 2;
  bool has_info() const;
  private:
  bool _internal_has_info() const;
  public:
  void clear_info();
  const ::galbot::navigation_proto::MapMetaData& info() const;
  ::galbot::navigation_proto::MapMetaData* release_info();
  ::galbot::navigation_proto::MapMetaData* mutable_info();
  void set_allocated_info(::galbot::navigation_proto::MapMetaData* info);
  private:
  const ::galbot::navigation_proto::MapMetaData& _internal_info() const;
  ::galbot::navigation_proto::MapMetaData* _internal_mutable_info();
  public:
  void unsafe_arena_set_allocated_info(
      ::galbot::navigation_proto::MapMetaData* info);
  ::galbot::navigation_proto::MapMetaData* unsafe_arena_release_info();

  // @@protoc_insertion_point(class_scope:galbot.navigation_proto.OccupancyGrid)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  ::galbot::core_proto::Header* header_;
  ::galbot::navigation_proto::MapMetaData* info_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fnavigation_5fproto_2fmap_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GridCells

// .galbot.core_proto.Header header = 1;
inline bool GridCells::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool GridCells::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& GridCells::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& GridCells::header() const {
  // @@protoc_insertion_point(field_get:galbot.navigation_proto.GridCells.header)
  return _internal_header();
}
inline void GridCells::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.navigation_proto.GridCells.header)
}
inline ::galbot::core_proto::Header* GridCells::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* GridCells::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.navigation_proto.GridCells.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* GridCells::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* GridCells::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.navigation_proto.GridCells.header)
  return _internal_mutable_header();
}
inline void GridCells::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.navigation_proto.GridCells.header)
}

// float cell_width = 2;
inline void GridCells::clear_cell_width() {
  cell_width_ = 0;
}
inline float GridCells::_internal_cell_width() const {
  return cell_width_;
}
inline float GridCells::cell_width() const {
  // @@protoc_insertion_point(field_get:galbot.navigation_proto.GridCells.cell_width)
  return _internal_cell_width();
}
inline void GridCells::_internal_set_cell_width(float value) {
  
  cell_width_ = value;
}
inline void GridCells::set_cell_width(float value) {
  _internal_set_cell_width(value);
  // @@protoc_insertion_point(field_set:galbot.navigation_proto.GridCells.cell_width)
}

// float cell_height = 3;
inline void GridCells::clear_cell_height() {
  cell_height_ = 0;
}
inline float GridCells::_internal_cell_height() const {
  return cell_height_;
}
inline float GridCells::cell_height() const {
  // @@protoc_insertion_point(field_get:galbot.navigation_proto.GridCells.cell_height)
  return _internal_cell_height();
}
inline void GridCells::_internal_set_cell_height(float value) {
  
  cell_height_ = value;
}
inline void GridCells::set_cell_height(float value) {
  _internal_set_cell_height(value);
  // @@protoc_insertion_point(field_set:galbot.navigation_proto.GridCells.cell_height)
}

// repeated .galbot.core_proto.Point cells = 4;
inline int GridCells::_internal_cells_size() const {
  return cells_.size();
}
inline int GridCells::cells_size() const {
  return _internal_cells_size();
}
inline ::galbot::core_proto::Point* GridCells::mutable_cells(int index) {
  // @@protoc_insertion_point(field_mutable:galbot.navigation_proto.GridCells.cells)
  return cells_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::galbot::core_proto::Point >*
GridCells::mutable_cells() {
  // @@protoc_insertion_point(field_mutable_list:galbot.navigation_proto.GridCells.cells)
  return &cells_;
}
inline const ::galbot::core_proto::Point& GridCells::_internal_cells(int index) const {
  return cells_.Get(index);
}
inline const ::galbot::core_proto::Point& GridCells::cells(int index) const {
  // @@protoc_insertion_point(field_get:galbot.navigation_proto.GridCells.cells)
  return _internal_cells(index);
}
inline ::galbot::core_proto::Point* GridCells::_internal_add_cells() {
  return cells_.Add();
}
inline ::galbot::core_proto::Point* GridCells::add_cells() {
  // @@protoc_insertion_point(field_add:galbot.navigation_proto.GridCells.cells)
  return _internal_add_cells();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::galbot::core_proto::Point >&
GridCells::cells() const {
  // @@protoc_insertion_point(field_list:galbot.navigation_proto.GridCells.cells)
  return cells_;
}

// -------------------------------------------------------------------

// MapMetaData

// .galbot.core_proto.Timestamp map_load_time = 1;
inline bool MapMetaData::_internal_has_map_load_time() const {
  return this != internal_default_instance() && map_load_time_ != nullptr;
}
inline bool MapMetaData::has_map_load_time() const {
  return _internal_has_map_load_time();
}
inline const ::galbot::core_proto::Timestamp& MapMetaData::_internal_map_load_time() const {
  const ::galbot::core_proto::Timestamp* p = map_load_time_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Timestamp&>(
      ::galbot::core_proto::_Timestamp_default_instance_);
}
inline const ::galbot::core_proto::Timestamp& MapMetaData::map_load_time() const {
  // @@protoc_insertion_point(field_get:galbot.navigation_proto.MapMetaData.map_load_time)
  return _internal_map_load_time();
}
inline void MapMetaData::unsafe_arena_set_allocated_map_load_time(
    ::galbot::core_proto::Timestamp* map_load_time) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(map_load_time_);
  }
  map_load_time_ = map_load_time;
  if (map_load_time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.navigation_proto.MapMetaData.map_load_time)
}
inline ::galbot::core_proto::Timestamp* MapMetaData::release_map_load_time() {
  
  ::galbot::core_proto::Timestamp* temp = map_load_time_;
  map_load_time_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Timestamp* MapMetaData::unsafe_arena_release_map_load_time() {
  // @@protoc_insertion_point(field_release:galbot.navigation_proto.MapMetaData.map_load_time)
  
  ::galbot::core_proto::Timestamp* temp = map_load_time_;
  map_load_time_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Timestamp* MapMetaData::_internal_mutable_map_load_time() {
  
  if (map_load_time_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Timestamp>(GetArena());
    map_load_time_ = p;
  }
  return map_load_time_;
}
inline ::galbot::core_proto::Timestamp* MapMetaData::mutable_map_load_time() {
  // @@protoc_insertion_point(field_mutable:galbot.navigation_proto.MapMetaData.map_load_time)
  return _internal_mutable_map_load_time();
}
inline void MapMetaData::set_allocated_map_load_time(::galbot::core_proto::Timestamp* map_load_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(map_load_time_);
  }
  if (map_load_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(map_load_time)->GetArena();
    if (message_arena != submessage_arena) {
      map_load_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, map_load_time, submessage_arena);
    }
    
  } else {
    
  }
  map_load_time_ = map_load_time;
  // @@protoc_insertion_point(field_set_allocated:galbot.navigation_proto.MapMetaData.map_load_time)
}

// float resolution = 2;
inline void MapMetaData::clear_resolution() {
  resolution_ = 0;
}
inline float MapMetaData::_internal_resolution() const {
  return resolution_;
}
inline float MapMetaData::resolution() const {
  // @@protoc_insertion_point(field_get:galbot.navigation_proto.MapMetaData.resolution)
  return _internal_resolution();
}
inline void MapMetaData::_internal_set_resolution(float value) {
  
  resolution_ = value;
}
inline void MapMetaData::set_resolution(float value) {
  _internal_set_resolution(value);
  // @@protoc_insertion_point(field_set:galbot.navigation_proto.MapMetaData.resolution)
}

// uint32 width = 3;
inline void MapMetaData::clear_width() {
  width_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MapMetaData::_internal_width() const {
  return width_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MapMetaData::width() const {
  // @@protoc_insertion_point(field_get:galbot.navigation_proto.MapMetaData.width)
  return _internal_width();
}
inline void MapMetaData::_internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  width_ = value;
}
inline void MapMetaData::set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:galbot.navigation_proto.MapMetaData.width)
}

// uint32 height = 4;
inline void MapMetaData::clear_height() {
  height_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MapMetaData::_internal_height() const {
  return height_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MapMetaData::height() const {
  // @@protoc_insertion_point(field_get:galbot.navigation_proto.MapMetaData.height)
  return _internal_height();
}
inline void MapMetaData::_internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  height_ = value;
}
inline void MapMetaData::set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:galbot.navigation_proto.MapMetaData.height)
}

// .galbot.spatial_proto.Pose origin = 5;
inline bool MapMetaData::_internal_has_origin() const {
  return this != internal_default_instance() && origin_ != nullptr;
}
inline bool MapMetaData::has_origin() const {
  return _internal_has_origin();
}
inline const ::galbot::spatial_proto::Pose& MapMetaData::_internal_origin() const {
  const ::galbot::spatial_proto::Pose* p = origin_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::spatial_proto::Pose&>(
      ::galbot::spatial_proto::_Pose_default_instance_);
}
inline const ::galbot::spatial_proto::Pose& MapMetaData::origin() const {
  // @@protoc_insertion_point(field_get:galbot.navigation_proto.MapMetaData.origin)
  return _internal_origin();
}
inline void MapMetaData::unsafe_arena_set_allocated_origin(
    ::galbot::spatial_proto::Pose* origin) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(origin_);
  }
  origin_ = origin;
  if (origin) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.navigation_proto.MapMetaData.origin)
}
inline ::galbot::spatial_proto::Pose* MapMetaData::release_origin() {
  
  ::galbot::spatial_proto::Pose* temp = origin_;
  origin_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::spatial_proto::Pose* MapMetaData::unsafe_arena_release_origin() {
  // @@protoc_insertion_point(field_release:galbot.navigation_proto.MapMetaData.origin)
  
  ::galbot::spatial_proto::Pose* temp = origin_;
  origin_ = nullptr;
  return temp;
}
inline ::galbot::spatial_proto::Pose* MapMetaData::_internal_mutable_origin() {
  
  if (origin_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::spatial_proto::Pose>(GetArena());
    origin_ = p;
  }
  return origin_;
}
inline ::galbot::spatial_proto::Pose* MapMetaData::mutable_origin() {
  // @@protoc_insertion_point(field_mutable:galbot.navigation_proto.MapMetaData.origin)
  return _internal_mutable_origin();
}
inline void MapMetaData::set_allocated_origin(::galbot::spatial_proto::Pose* origin) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(origin_);
  }
  if (origin) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(origin)->GetArena();
    if (message_arena != submessage_arena) {
      origin = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, origin, submessage_arena);
    }
    
  } else {
    
  }
  origin_ = origin;
  // @@protoc_insertion_point(field_set_allocated:galbot.navigation_proto.MapMetaData.origin)
}

// -------------------------------------------------------------------

// OccupancyGrid

// .galbot.core_proto.Header header = 1;
inline bool OccupancyGrid::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool OccupancyGrid::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& OccupancyGrid::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& OccupancyGrid::header() const {
  // @@protoc_insertion_point(field_get:galbot.navigation_proto.OccupancyGrid.header)
  return _internal_header();
}
inline void OccupancyGrid::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.navigation_proto.OccupancyGrid.header)
}
inline ::galbot::core_proto::Header* OccupancyGrid::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* OccupancyGrid::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.navigation_proto.OccupancyGrid.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* OccupancyGrid::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* OccupancyGrid::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.navigation_proto.OccupancyGrid.header)
  return _internal_mutable_header();
}
inline void OccupancyGrid::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.navigation_proto.OccupancyGrid.header)
}

// .galbot.navigation_proto.MapMetaData info = 2;
inline bool OccupancyGrid::_internal_has_info() const {
  return this != internal_default_instance() && info_ != nullptr;
}
inline bool OccupancyGrid::has_info() const {
  return _internal_has_info();
}
inline void OccupancyGrid::clear_info() {
  if (GetArena() == nullptr && info_ != nullptr) {
    delete info_;
  }
  info_ = nullptr;
}
inline const ::galbot::navigation_proto::MapMetaData& OccupancyGrid::_internal_info() const {
  const ::galbot::navigation_proto::MapMetaData* p = info_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::navigation_proto::MapMetaData&>(
      ::galbot::navigation_proto::_MapMetaData_default_instance_);
}
inline const ::galbot::navigation_proto::MapMetaData& OccupancyGrid::info() const {
  // @@protoc_insertion_point(field_get:galbot.navigation_proto.OccupancyGrid.info)
  return _internal_info();
}
inline void OccupancyGrid::unsafe_arena_set_allocated_info(
    ::galbot::navigation_proto::MapMetaData* info) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(info_);
  }
  info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.navigation_proto.OccupancyGrid.info)
}
inline ::galbot::navigation_proto::MapMetaData* OccupancyGrid::release_info() {
  
  ::galbot::navigation_proto::MapMetaData* temp = info_;
  info_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::navigation_proto::MapMetaData* OccupancyGrid::unsafe_arena_release_info() {
  // @@protoc_insertion_point(field_release:galbot.navigation_proto.OccupancyGrid.info)
  
  ::galbot::navigation_proto::MapMetaData* temp = info_;
  info_ = nullptr;
  return temp;
}
inline ::galbot::navigation_proto::MapMetaData* OccupancyGrid::_internal_mutable_info() {
  
  if (info_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::navigation_proto::MapMetaData>(GetArena());
    info_ = p;
  }
  return info_;
}
inline ::galbot::navigation_proto::MapMetaData* OccupancyGrid::mutable_info() {
  // @@protoc_insertion_point(field_mutable:galbot.navigation_proto.OccupancyGrid.info)
  return _internal_mutable_info();
}
inline void OccupancyGrid::set_allocated_info(::galbot::navigation_proto::MapMetaData* info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete info_;
  }
  if (info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(info);
    if (message_arena != submessage_arena) {
      info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, info, submessage_arena);
    }
    
  } else {
    
  }
  info_ = info;
  // @@protoc_insertion_point(field_set_allocated:galbot.navigation_proto.OccupancyGrid.info)
}

// bytes data = 3;
inline void OccupancyGrid::clear_data() {
  data_.ClearToEmpty();
}
inline const std::string& OccupancyGrid::data() const {
  // @@protoc_insertion_point(field_get:galbot.navigation_proto.OccupancyGrid.data)
  return _internal_data();
}
inline void OccupancyGrid::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:galbot.navigation_proto.OccupancyGrid.data)
}
inline std::string* OccupancyGrid::mutable_data() {
  // @@protoc_insertion_point(field_mutable:galbot.navigation_proto.OccupancyGrid.data)
  return _internal_mutable_data();
}
inline const std::string& OccupancyGrid::_internal_data() const {
  return data_.Get();
}
inline void OccupancyGrid::_internal_set_data(const std::string& value) {
  
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void OccupancyGrid::set_data(std::string&& value) {
  
  data_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.navigation_proto.OccupancyGrid.data)
}
inline void OccupancyGrid::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.navigation_proto.OccupancyGrid.data)
}
inline void OccupancyGrid::set_data(const void* value,
    size_t size) {
  
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.navigation_proto.OccupancyGrid.data)
}
inline std::string* OccupancyGrid::_internal_mutable_data() {
  
  return data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* OccupancyGrid::release_data() {
  // @@protoc_insertion_point(field_release:galbot.navigation_proto.OccupancyGrid.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void OccupancyGrid::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.navigation_proto.OccupancyGrid.data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace navigation_proto
}  // namespace galbot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fnavigation_5fproto_2fmap_2eproto
