// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/sensor_proto/camera.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fsensor_5fproto_2fcamera_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fsensor_5fproto_2fcamera_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "galbot/core_proto/header.pb.h"
#include "galbot/sensor_proto/roi.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fsensor_5fproto_2fcamera_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fsensor_5fproto_2fcamera_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fsensor_5fproto_2fcamera_2eproto;
namespace galbot {
namespace sensor_proto {
class CameraInfo;
class CameraInfoDefaultTypeInternal;
extern CameraInfoDefaultTypeInternal _CameraInfo_default_instance_;
}  // namespace sensor_proto
}  // namespace galbot
PROTOBUF_NAMESPACE_OPEN
template<> ::galbot::sensor_proto::CameraInfo* Arena::CreateMaybeMessage<::galbot::sensor_proto::CameraInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace sensor_proto {

// ===================================================================

class CameraInfo PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.sensor_proto.CameraInfo) */ {
 public:
  inline CameraInfo() : CameraInfo(nullptr) {}
  virtual ~CameraInfo();

  CameraInfo(const CameraInfo& from);
  CameraInfo(CameraInfo&& from) noexcept
    : CameraInfo() {
    *this = ::std::move(from);
  }

  inline CameraInfo& operator=(const CameraInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline CameraInfo& operator=(CameraInfo&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CameraInfo& default_instance();

  static inline const CameraInfo* internal_default_instance() {
    return reinterpret_cast<const CameraInfo*>(
               &_CameraInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CameraInfo& a, CameraInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(CameraInfo* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CameraInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CameraInfo* New() const final {
    return CreateMaybeMessage<CameraInfo>(nullptr);
  }

  CameraInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CameraInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CameraInfo& from);
  void MergeFrom(const CameraInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CameraInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.sensor_proto.CameraInfo";
  }
  protected:
  explicit CameraInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsensor_5fproto_2fcamera_2eproto);
    return ::descriptor_table_galbot_2fsensor_5fproto_2fcamera_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDFieldNumber = 5,
    kKFieldNumber = 6,
    kRFieldNumber = 7,
    kPFieldNumber = 8,
    kTFieldNumber = 13,
    kDistortionModelFieldNumber = 4,
    kCameraTypeFieldNumber = 12,
    kHeaderFieldNumber = 1,
    kRoiFieldNumber = 11,
    kHeightFieldNumber = 2,
    kWidthFieldNumber = 3,
    kBinningXFieldNumber = 9,
    kBinningYFieldNumber = 10,
  };
  // repeated double d = 5;
  int d_size() const;
  private:
  int _internal_d_size() const;
  public:
  void clear_d();
  private:
  double _internal_d(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_d() const;
  void _internal_add_d(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_d();
  public:
  double d(int index) const;
  void set_d(int index, double value);
  void add_d(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      d() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_d();

  // repeated double k = 6;
  int k_size() const;
  private:
  int _internal_k_size() const;
  public:
  void clear_k();
  private:
  double _internal_k(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_k() const;
  void _internal_add_k(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_k();
  public:
  double k(int index) const;
  void set_k(int index, double value);
  void add_k(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      k() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_k();

  // repeated double r = 7;
  int r_size() const;
  private:
  int _internal_r_size() const;
  public:
  void clear_r();
  private:
  double _internal_r(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_r() const;
  void _internal_add_r(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_r();
  public:
  double r(int index) const;
  void set_r(int index, double value);
  void add_r(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      r() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_r();

  // repeated double p = 8;
  int p_size() const;
  private:
  int _internal_p_size() const;
  public:
  void clear_p();
  private:
  double _internal_p(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_p() const;
  void _internal_add_p(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_p();
  public:
  double p(int index) const;
  void set_p(int index, double value);
  void add_p(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      p() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_p();

  // repeated double T = 13;
  int t_size() const;
  private:
  int _internal_t_size() const;
  public:
  void clear_t();
  private:
  double _internal_t(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_t() const;
  void _internal_add_t(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_t();
  public:
  double t(int index) const;
  void set_t(int index, double value);
  void add_t(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      t() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_t();

  // string distortion_model = 4;
  void clear_distortion_model();
  const std::string& distortion_model() const;
  void set_distortion_model(const std::string& value);
  void set_distortion_model(std::string&& value);
  void set_distortion_model(const char* value);
  void set_distortion_model(const char* value, size_t size);
  std::string* mutable_distortion_model();
  std::string* release_distortion_model();
  void set_allocated_distortion_model(std::string* distortion_model);
  private:
  const std::string& _internal_distortion_model() const;
  void _internal_set_distortion_model(const std::string& value);
  std::string* _internal_mutable_distortion_model();
  public:

  // string camera_type = 12;
  void clear_camera_type();
  const std::string& camera_type() const;
  void set_camera_type(const std::string& value);
  void set_camera_type(std::string&& value);
  void set_camera_type(const char* value);
  void set_camera_type(const char* value, size_t size);
  std::string* mutable_camera_type();
  std::string* release_camera_type();
  void set_allocated_camera_type(std::string* camera_type);
  private:
  const std::string& _internal_camera_type() const;
  void _internal_set_camera_type(const std::string& value);
  std::string* _internal_mutable_camera_type();
  public:

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // .galbot.sensor_proto.RegionOfInterest roi = 11;
  bool has_roi() const;
  private:
  bool _internal_has_roi() const;
  public:
  void clear_roi();
  const ::galbot::sensor_proto::RegionOfInterest& roi() const;
  ::galbot::sensor_proto::RegionOfInterest* release_roi();
  ::galbot::sensor_proto::RegionOfInterest* mutable_roi();
  void set_allocated_roi(::galbot::sensor_proto::RegionOfInterest* roi);
  private:
  const ::galbot::sensor_proto::RegionOfInterest& _internal_roi() const;
  ::galbot::sensor_proto::RegionOfInterest* _internal_mutable_roi();
  public:
  void unsafe_arena_set_allocated_roi(
      ::galbot::sensor_proto::RegionOfInterest* roi);
  ::galbot::sensor_proto::RegionOfInterest* unsafe_arena_release_roi();

  // uint32 height = 2;
  void clear_height();
  ::PROTOBUF_NAMESPACE_ID::uint32 height() const;
  void set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_height() const;
  void _internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 width = 3;
  void clear_width();
  ::PROTOBUF_NAMESPACE_ID::uint32 width() const;
  void set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_width() const;
  void _internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 binning_x = 9;
  void clear_binning_x();
  ::PROTOBUF_NAMESPACE_ID::uint32 binning_x() const;
  void set_binning_x(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_binning_x() const;
  void _internal_set_binning_x(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 binning_y = 10;
  void clear_binning_y();
  ::PROTOBUF_NAMESPACE_ID::uint32 binning_y() const;
  void set_binning_y(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_binning_y() const;
  void _internal_set_binning_y(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.sensor_proto.CameraInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > d_;
  mutable std::atomic<int> _d_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > k_;
  mutable std::atomic<int> _k_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > r_;
  mutable std::atomic<int> _r_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > p_;
  mutable std::atomic<int> _p_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > t_;
  mutable std::atomic<int> _t_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr distortion_model_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr camera_type_;
  ::galbot::core_proto::Header* header_;
  ::galbot::sensor_proto::RegionOfInterest* roi_;
  ::PROTOBUF_NAMESPACE_ID::uint32 height_;
  ::PROTOBUF_NAMESPACE_ID::uint32 width_;
  ::PROTOBUF_NAMESPACE_ID::uint32 binning_x_;
  ::PROTOBUF_NAMESPACE_ID::uint32 binning_y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsensor_5fproto_2fcamera_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CameraInfo

// .galbot.core_proto.Header header = 1;
inline bool CameraInfo::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool CameraInfo::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& CameraInfo::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& CameraInfo::header() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.CameraInfo.header)
  return _internal_header();
}
inline void CameraInfo::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.sensor_proto.CameraInfo.header)
}
inline ::galbot::core_proto::Header* CameraInfo::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* CameraInfo::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.sensor_proto.CameraInfo.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* CameraInfo::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* CameraInfo::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.sensor_proto.CameraInfo.header)
  return _internal_mutable_header();
}
inline void CameraInfo::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.sensor_proto.CameraInfo.header)
}

// uint32 height = 2;
inline void CameraInfo::clear_height() {
  height_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CameraInfo::_internal_height() const {
  return height_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CameraInfo::height() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.CameraInfo.height)
  return _internal_height();
}
inline void CameraInfo::_internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  height_ = value;
}
inline void CameraInfo::set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.CameraInfo.height)
}

// uint32 width = 3;
inline void CameraInfo::clear_width() {
  width_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CameraInfo::_internal_width() const {
  return width_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CameraInfo::width() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.CameraInfo.width)
  return _internal_width();
}
inline void CameraInfo::_internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  width_ = value;
}
inline void CameraInfo::set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.CameraInfo.width)
}

// string distortion_model = 4;
inline void CameraInfo::clear_distortion_model() {
  distortion_model_.ClearToEmpty();
}
inline const std::string& CameraInfo::distortion_model() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.CameraInfo.distortion_model)
  return _internal_distortion_model();
}
inline void CameraInfo::set_distortion_model(const std::string& value) {
  _internal_set_distortion_model(value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.CameraInfo.distortion_model)
}
inline std::string* CameraInfo::mutable_distortion_model() {
  // @@protoc_insertion_point(field_mutable:galbot.sensor_proto.CameraInfo.distortion_model)
  return _internal_mutable_distortion_model();
}
inline const std::string& CameraInfo::_internal_distortion_model() const {
  return distortion_model_.Get();
}
inline void CameraInfo::_internal_set_distortion_model(const std::string& value) {
  
  distortion_model_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CameraInfo::set_distortion_model(std::string&& value) {
  
  distortion_model_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.sensor_proto.CameraInfo.distortion_model)
}
inline void CameraInfo::set_distortion_model(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  distortion_model_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.sensor_proto.CameraInfo.distortion_model)
}
inline void CameraInfo::set_distortion_model(const char* value,
    size_t size) {
  
  distortion_model_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.sensor_proto.CameraInfo.distortion_model)
}
inline std::string* CameraInfo::_internal_mutable_distortion_model() {
  
  return distortion_model_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CameraInfo::release_distortion_model() {
  // @@protoc_insertion_point(field_release:galbot.sensor_proto.CameraInfo.distortion_model)
  return distortion_model_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CameraInfo::set_allocated_distortion_model(std::string* distortion_model) {
  if (distortion_model != nullptr) {
    
  } else {
    
  }
  distortion_model_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), distortion_model,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.sensor_proto.CameraInfo.distortion_model)
}

// repeated double d = 5;
inline int CameraInfo::_internal_d_size() const {
  return d_.size();
}
inline int CameraInfo::d_size() const {
  return _internal_d_size();
}
inline void CameraInfo::clear_d() {
  d_.Clear();
}
inline double CameraInfo::_internal_d(int index) const {
  return d_.Get(index);
}
inline double CameraInfo::d(int index) const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.CameraInfo.d)
  return _internal_d(index);
}
inline void CameraInfo::set_d(int index, double value) {
  d_.Set(index, value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.CameraInfo.d)
}
inline void CameraInfo::_internal_add_d(double value) {
  d_.Add(value);
}
inline void CameraInfo::add_d(double value) {
  _internal_add_d(value);
  // @@protoc_insertion_point(field_add:galbot.sensor_proto.CameraInfo.d)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
CameraInfo::_internal_d() const {
  return d_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
CameraInfo::d() const {
  // @@protoc_insertion_point(field_list:galbot.sensor_proto.CameraInfo.d)
  return _internal_d();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
CameraInfo::_internal_mutable_d() {
  return &d_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
CameraInfo::mutable_d() {
  // @@protoc_insertion_point(field_mutable_list:galbot.sensor_proto.CameraInfo.d)
  return _internal_mutable_d();
}

// repeated double k = 6;
inline int CameraInfo::_internal_k_size() const {
  return k_.size();
}
inline int CameraInfo::k_size() const {
  return _internal_k_size();
}
inline void CameraInfo::clear_k() {
  k_.Clear();
}
inline double CameraInfo::_internal_k(int index) const {
  return k_.Get(index);
}
inline double CameraInfo::k(int index) const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.CameraInfo.k)
  return _internal_k(index);
}
inline void CameraInfo::set_k(int index, double value) {
  k_.Set(index, value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.CameraInfo.k)
}
inline void CameraInfo::_internal_add_k(double value) {
  k_.Add(value);
}
inline void CameraInfo::add_k(double value) {
  _internal_add_k(value);
  // @@protoc_insertion_point(field_add:galbot.sensor_proto.CameraInfo.k)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
CameraInfo::_internal_k() const {
  return k_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
CameraInfo::k() const {
  // @@protoc_insertion_point(field_list:galbot.sensor_proto.CameraInfo.k)
  return _internal_k();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
CameraInfo::_internal_mutable_k() {
  return &k_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
CameraInfo::mutable_k() {
  // @@protoc_insertion_point(field_mutable_list:galbot.sensor_proto.CameraInfo.k)
  return _internal_mutable_k();
}

// repeated double r = 7;
inline int CameraInfo::_internal_r_size() const {
  return r_.size();
}
inline int CameraInfo::r_size() const {
  return _internal_r_size();
}
inline void CameraInfo::clear_r() {
  r_.Clear();
}
inline double CameraInfo::_internal_r(int index) const {
  return r_.Get(index);
}
inline double CameraInfo::r(int index) const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.CameraInfo.r)
  return _internal_r(index);
}
inline void CameraInfo::set_r(int index, double value) {
  r_.Set(index, value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.CameraInfo.r)
}
inline void CameraInfo::_internal_add_r(double value) {
  r_.Add(value);
}
inline void CameraInfo::add_r(double value) {
  _internal_add_r(value);
  // @@protoc_insertion_point(field_add:galbot.sensor_proto.CameraInfo.r)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
CameraInfo::_internal_r() const {
  return r_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
CameraInfo::r() const {
  // @@protoc_insertion_point(field_list:galbot.sensor_proto.CameraInfo.r)
  return _internal_r();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
CameraInfo::_internal_mutable_r() {
  return &r_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
CameraInfo::mutable_r() {
  // @@protoc_insertion_point(field_mutable_list:galbot.sensor_proto.CameraInfo.r)
  return _internal_mutable_r();
}

// repeated double p = 8;
inline int CameraInfo::_internal_p_size() const {
  return p_.size();
}
inline int CameraInfo::p_size() const {
  return _internal_p_size();
}
inline void CameraInfo::clear_p() {
  p_.Clear();
}
inline double CameraInfo::_internal_p(int index) const {
  return p_.Get(index);
}
inline double CameraInfo::p(int index) const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.CameraInfo.p)
  return _internal_p(index);
}
inline void CameraInfo::set_p(int index, double value) {
  p_.Set(index, value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.CameraInfo.p)
}
inline void CameraInfo::_internal_add_p(double value) {
  p_.Add(value);
}
inline void CameraInfo::add_p(double value) {
  _internal_add_p(value);
  // @@protoc_insertion_point(field_add:galbot.sensor_proto.CameraInfo.p)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
CameraInfo::_internal_p() const {
  return p_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
CameraInfo::p() const {
  // @@protoc_insertion_point(field_list:galbot.sensor_proto.CameraInfo.p)
  return _internal_p();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
CameraInfo::_internal_mutable_p() {
  return &p_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
CameraInfo::mutable_p() {
  // @@protoc_insertion_point(field_mutable_list:galbot.sensor_proto.CameraInfo.p)
  return _internal_mutable_p();
}

// uint32 binning_x = 9;
inline void CameraInfo::clear_binning_x() {
  binning_x_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CameraInfo::_internal_binning_x() const {
  return binning_x_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CameraInfo::binning_x() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.CameraInfo.binning_x)
  return _internal_binning_x();
}
inline void CameraInfo::_internal_set_binning_x(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  binning_x_ = value;
}
inline void CameraInfo::set_binning_x(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_binning_x(value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.CameraInfo.binning_x)
}

// uint32 binning_y = 10;
inline void CameraInfo::clear_binning_y() {
  binning_y_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CameraInfo::_internal_binning_y() const {
  return binning_y_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CameraInfo::binning_y() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.CameraInfo.binning_y)
  return _internal_binning_y();
}
inline void CameraInfo::_internal_set_binning_y(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  binning_y_ = value;
}
inline void CameraInfo::set_binning_y(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_binning_y(value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.CameraInfo.binning_y)
}

// .galbot.sensor_proto.RegionOfInterest roi = 11;
inline bool CameraInfo::_internal_has_roi() const {
  return this != internal_default_instance() && roi_ != nullptr;
}
inline bool CameraInfo::has_roi() const {
  return _internal_has_roi();
}
inline const ::galbot::sensor_proto::RegionOfInterest& CameraInfo::_internal_roi() const {
  const ::galbot::sensor_proto::RegionOfInterest* p = roi_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::sensor_proto::RegionOfInterest&>(
      ::galbot::sensor_proto::_RegionOfInterest_default_instance_);
}
inline const ::galbot::sensor_proto::RegionOfInterest& CameraInfo::roi() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.CameraInfo.roi)
  return _internal_roi();
}
inline void CameraInfo::unsafe_arena_set_allocated_roi(
    ::galbot::sensor_proto::RegionOfInterest* roi) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(roi_);
  }
  roi_ = roi;
  if (roi) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.sensor_proto.CameraInfo.roi)
}
inline ::galbot::sensor_proto::RegionOfInterest* CameraInfo::release_roi() {
  
  ::galbot::sensor_proto::RegionOfInterest* temp = roi_;
  roi_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::sensor_proto::RegionOfInterest* CameraInfo::unsafe_arena_release_roi() {
  // @@protoc_insertion_point(field_release:galbot.sensor_proto.CameraInfo.roi)
  
  ::galbot::sensor_proto::RegionOfInterest* temp = roi_;
  roi_ = nullptr;
  return temp;
}
inline ::galbot::sensor_proto::RegionOfInterest* CameraInfo::_internal_mutable_roi() {
  
  if (roi_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::sensor_proto::RegionOfInterest>(GetArena());
    roi_ = p;
  }
  return roi_;
}
inline ::galbot::sensor_proto::RegionOfInterest* CameraInfo::mutable_roi() {
  // @@protoc_insertion_point(field_mutable:galbot.sensor_proto.CameraInfo.roi)
  return _internal_mutable_roi();
}
inline void CameraInfo::set_allocated_roi(::galbot::sensor_proto::RegionOfInterest* roi) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(roi_);
  }
  if (roi) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(roi)->GetArena();
    if (message_arena != submessage_arena) {
      roi = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, roi, submessage_arena);
    }
    
  } else {
    
  }
  roi_ = roi;
  // @@protoc_insertion_point(field_set_allocated:galbot.sensor_proto.CameraInfo.roi)
}

// string camera_type = 12;
inline void CameraInfo::clear_camera_type() {
  camera_type_.ClearToEmpty();
}
inline const std::string& CameraInfo::camera_type() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.CameraInfo.camera_type)
  return _internal_camera_type();
}
inline void CameraInfo::set_camera_type(const std::string& value) {
  _internal_set_camera_type(value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.CameraInfo.camera_type)
}
inline std::string* CameraInfo::mutable_camera_type() {
  // @@protoc_insertion_point(field_mutable:galbot.sensor_proto.CameraInfo.camera_type)
  return _internal_mutable_camera_type();
}
inline const std::string& CameraInfo::_internal_camera_type() const {
  return camera_type_.Get();
}
inline void CameraInfo::_internal_set_camera_type(const std::string& value) {
  
  camera_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CameraInfo::set_camera_type(std::string&& value) {
  
  camera_type_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.sensor_proto.CameraInfo.camera_type)
}
inline void CameraInfo::set_camera_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  camera_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.sensor_proto.CameraInfo.camera_type)
}
inline void CameraInfo::set_camera_type(const char* value,
    size_t size) {
  
  camera_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.sensor_proto.CameraInfo.camera_type)
}
inline std::string* CameraInfo::_internal_mutable_camera_type() {
  
  return camera_type_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CameraInfo::release_camera_type() {
  // @@protoc_insertion_point(field_release:galbot.sensor_proto.CameraInfo.camera_type)
  return camera_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CameraInfo::set_allocated_camera_type(std::string* camera_type) {
  if (camera_type != nullptr) {
    
  } else {
    
  }
  camera_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), camera_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.sensor_proto.CameraInfo.camera_type)
}

// repeated double T = 13;
inline int CameraInfo::_internal_t_size() const {
  return t_.size();
}
inline int CameraInfo::t_size() const {
  return _internal_t_size();
}
inline void CameraInfo::clear_t() {
  t_.Clear();
}
inline double CameraInfo::_internal_t(int index) const {
  return t_.Get(index);
}
inline double CameraInfo::t(int index) const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.CameraInfo.T)
  return _internal_t(index);
}
inline void CameraInfo::set_t(int index, double value) {
  t_.Set(index, value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.CameraInfo.T)
}
inline void CameraInfo::_internal_add_t(double value) {
  t_.Add(value);
}
inline void CameraInfo::add_t(double value) {
  _internal_add_t(value);
  // @@protoc_insertion_point(field_add:galbot.sensor_proto.CameraInfo.T)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
CameraInfo::_internal_t() const {
  return t_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
CameraInfo::t() const {
  // @@protoc_insertion_point(field_list:galbot.sensor_proto.CameraInfo.T)
  return _internal_t();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
CameraInfo::_internal_mutable_t() {
  return &t_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
CameraInfo::mutable_t() {
  // @@protoc_insertion_point(field_mutable_list:galbot.sensor_proto.CameraInfo.T)
  return _internal_mutable_t();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace sensor_proto
}  // namespace galbot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fsensor_5fproto_2fcamera_2eproto
