// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/sensor_proto/physical_quantity.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "galbot/core_proto/header.pb.h"
#include "galbot/core_proto/math.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto;
namespace galbot {
namespace sensor_proto {
class FluidPressure;
class FluidPressureDefaultTypeInternal;
extern FluidPressureDefaultTypeInternal _FluidPressure_default_instance_;
class Illuminance;
class IlluminanceDefaultTypeInternal;
extern IlluminanceDefaultTypeInternal _Illuminance_default_instance_;
class MagneticField;
class MagneticFieldDefaultTypeInternal;
extern MagneticFieldDefaultTypeInternal _MagneticField_default_instance_;
class RelativeHumidity;
class RelativeHumidityDefaultTypeInternal;
extern RelativeHumidityDefaultTypeInternal _RelativeHumidity_default_instance_;
class Temperature;
class TemperatureDefaultTypeInternal;
extern TemperatureDefaultTypeInternal _Temperature_default_instance_;
}  // namespace sensor_proto
}  // namespace galbot
PROTOBUF_NAMESPACE_OPEN
template<> ::galbot::sensor_proto::FluidPressure* Arena::CreateMaybeMessage<::galbot::sensor_proto::FluidPressure>(Arena*);
template<> ::galbot::sensor_proto::Illuminance* Arena::CreateMaybeMessage<::galbot::sensor_proto::Illuminance>(Arena*);
template<> ::galbot::sensor_proto::MagneticField* Arena::CreateMaybeMessage<::galbot::sensor_proto::MagneticField>(Arena*);
template<> ::galbot::sensor_proto::RelativeHumidity* Arena::CreateMaybeMessage<::galbot::sensor_proto::RelativeHumidity>(Arena*);
template<> ::galbot::sensor_proto::Temperature* Arena::CreateMaybeMessage<::galbot::sensor_proto::Temperature>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace sensor_proto {

// ===================================================================

class FluidPressure PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.sensor_proto.FluidPressure) */ {
 public:
  inline FluidPressure() : FluidPressure(nullptr) {}
  virtual ~FluidPressure();

  FluidPressure(const FluidPressure& from);
  FluidPressure(FluidPressure&& from) noexcept
    : FluidPressure() {
    *this = ::std::move(from);
  }

  inline FluidPressure& operator=(const FluidPressure& from) {
    CopyFrom(from);
    return *this;
  }
  inline FluidPressure& operator=(FluidPressure&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FluidPressure& default_instance();

  static inline const FluidPressure* internal_default_instance() {
    return reinterpret_cast<const FluidPressure*>(
               &_FluidPressure_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FluidPressure& a, FluidPressure& b) {
    a.Swap(&b);
  }
  inline void Swap(FluidPressure* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FluidPressure* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FluidPressure* New() const final {
    return CreateMaybeMessage<FluidPressure>(nullptr);
  }

  FluidPressure* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FluidPressure>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FluidPressure& from);
  void MergeFrom(const FluidPressure& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FluidPressure* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.sensor_proto.FluidPressure";
  }
  protected:
  explicit FluidPressure(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto);
    return ::descriptor_table_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kFluidPressureFieldNumber = 2,
    kVarianceFieldNumber = 3,
  };
  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // double fluid_pressure = 2;
  void clear_fluid_pressure();
  double fluid_pressure() const;
  void set_fluid_pressure(double value);
  private:
  double _internal_fluid_pressure() const;
  void _internal_set_fluid_pressure(double value);
  public:

  // double variance = 3;
  void clear_variance();
  double variance() const;
  void set_variance(double value);
  private:
  double _internal_variance() const;
  void _internal_set_variance(double value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.sensor_proto.FluidPressure)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::galbot::core_proto::Header* header_;
  double fluid_pressure_;
  double variance_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto;
};
// -------------------------------------------------------------------

class Illuminance PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.sensor_proto.Illuminance) */ {
 public:
  inline Illuminance() : Illuminance(nullptr) {}
  virtual ~Illuminance();

  Illuminance(const Illuminance& from);
  Illuminance(Illuminance&& from) noexcept
    : Illuminance() {
    *this = ::std::move(from);
  }

  inline Illuminance& operator=(const Illuminance& from) {
    CopyFrom(from);
    return *this;
  }
  inline Illuminance& operator=(Illuminance&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Illuminance& default_instance();

  static inline const Illuminance* internal_default_instance() {
    return reinterpret_cast<const Illuminance*>(
               &_Illuminance_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Illuminance& a, Illuminance& b) {
    a.Swap(&b);
  }
  inline void Swap(Illuminance* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Illuminance* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Illuminance* New() const final {
    return CreateMaybeMessage<Illuminance>(nullptr);
  }

  Illuminance* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Illuminance>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Illuminance& from);
  void MergeFrom(const Illuminance& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Illuminance* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.sensor_proto.Illuminance";
  }
  protected:
  explicit Illuminance(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto);
    return ::descriptor_table_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kIlluminanceFieldNumber = 2,
    kVarianceFieldNumber = 3,
  };
  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // double illuminance = 2;
  void clear_illuminance();
  double illuminance() const;
  void set_illuminance(double value);
  private:
  double _internal_illuminance() const;
  void _internal_set_illuminance(double value);
  public:

  // double variance = 3;
  void clear_variance();
  double variance() const;
  void set_variance(double value);
  private:
  double _internal_variance() const;
  void _internal_set_variance(double value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.sensor_proto.Illuminance)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::galbot::core_proto::Header* header_;
  double illuminance_;
  double variance_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto;
};
// -------------------------------------------------------------------

class MagneticField PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.sensor_proto.MagneticField) */ {
 public:
  inline MagneticField() : MagneticField(nullptr) {}
  virtual ~MagneticField();

  MagneticField(const MagneticField& from);
  MagneticField(MagneticField&& from) noexcept
    : MagneticField() {
    *this = ::std::move(from);
  }

  inline MagneticField& operator=(const MagneticField& from) {
    CopyFrom(from);
    return *this;
  }
  inline MagneticField& operator=(MagneticField&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MagneticField& default_instance();

  static inline const MagneticField* internal_default_instance() {
    return reinterpret_cast<const MagneticField*>(
               &_MagneticField_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MagneticField& a, MagneticField& b) {
    a.Swap(&b);
  }
  inline void Swap(MagneticField* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MagneticField* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MagneticField* New() const final {
    return CreateMaybeMessage<MagneticField>(nullptr);
  }

  MagneticField* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MagneticField>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MagneticField& from);
  void MergeFrom(const MagneticField& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MagneticField* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.sensor_proto.MagneticField";
  }
  protected:
  explicit MagneticField(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto);
    return ::descriptor_table_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kMagneticFieldFieldNumber = 2,
    kMagneticFieldCovarianceFieldNumber = 3,
  };
  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // .galbot.core_proto.Vector3 magnetic_field = 2;
  bool has_magnetic_field() const;
  private:
  bool _internal_has_magnetic_field() const;
  public:
  void clear_magnetic_field();
  const ::galbot::core_proto::Vector3& magnetic_field() const;
  ::galbot::core_proto::Vector3* release_magnetic_field();
  ::galbot::core_proto::Vector3* mutable_magnetic_field();
  void set_allocated_magnetic_field(::galbot::core_proto::Vector3* magnetic_field);
  private:
  const ::galbot::core_proto::Vector3& _internal_magnetic_field() const;
  ::galbot::core_proto::Vector3* _internal_mutable_magnetic_field();
  public:
  void unsafe_arena_set_allocated_magnetic_field(
      ::galbot::core_proto::Vector3* magnetic_field);
  ::galbot::core_proto::Vector3* unsafe_arena_release_magnetic_field();

  // .galbot.core_proto.Covariance3d magnetic_field_covariance = 3;
  bool has_magnetic_field_covariance() const;
  private:
  bool _internal_has_magnetic_field_covariance() const;
  public:
  void clear_magnetic_field_covariance();
  const ::galbot::core_proto::Covariance3d& magnetic_field_covariance() const;
  ::galbot::core_proto::Covariance3d* release_magnetic_field_covariance();
  ::galbot::core_proto::Covariance3d* mutable_magnetic_field_covariance();
  void set_allocated_magnetic_field_covariance(::galbot::core_proto::Covariance3d* magnetic_field_covariance);
  private:
  const ::galbot::core_proto::Covariance3d& _internal_magnetic_field_covariance() const;
  ::galbot::core_proto::Covariance3d* _internal_mutable_magnetic_field_covariance();
  public:
  void unsafe_arena_set_allocated_magnetic_field_covariance(
      ::galbot::core_proto::Covariance3d* magnetic_field_covariance);
  ::galbot::core_proto::Covariance3d* unsafe_arena_release_magnetic_field_covariance();

  // @@protoc_insertion_point(class_scope:galbot.sensor_proto.MagneticField)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::galbot::core_proto::Header* header_;
  ::galbot::core_proto::Vector3* magnetic_field_;
  ::galbot::core_proto::Covariance3d* magnetic_field_covariance_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto;
};
// -------------------------------------------------------------------

class RelativeHumidity PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.sensor_proto.RelativeHumidity) */ {
 public:
  inline RelativeHumidity() : RelativeHumidity(nullptr) {}
  virtual ~RelativeHumidity();

  RelativeHumidity(const RelativeHumidity& from);
  RelativeHumidity(RelativeHumidity&& from) noexcept
    : RelativeHumidity() {
    *this = ::std::move(from);
  }

  inline RelativeHumidity& operator=(const RelativeHumidity& from) {
    CopyFrom(from);
    return *this;
  }
  inline RelativeHumidity& operator=(RelativeHumidity&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RelativeHumidity& default_instance();

  static inline const RelativeHumidity* internal_default_instance() {
    return reinterpret_cast<const RelativeHumidity*>(
               &_RelativeHumidity_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(RelativeHumidity& a, RelativeHumidity& b) {
    a.Swap(&b);
  }
  inline void Swap(RelativeHumidity* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RelativeHumidity* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RelativeHumidity* New() const final {
    return CreateMaybeMessage<RelativeHumidity>(nullptr);
  }

  RelativeHumidity* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RelativeHumidity>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RelativeHumidity& from);
  void MergeFrom(const RelativeHumidity& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RelativeHumidity* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.sensor_proto.RelativeHumidity";
  }
  protected:
  explicit RelativeHumidity(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto);
    return ::descriptor_table_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kRelativeHumidityFieldNumber = 2,
    kVarianceFieldNumber = 3,
  };
  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // double relative_humidity = 2;
  void clear_relative_humidity();
  double relative_humidity() const;
  void set_relative_humidity(double value);
  private:
  double _internal_relative_humidity() const;
  void _internal_set_relative_humidity(double value);
  public:

  // double variance = 3;
  void clear_variance();
  double variance() const;
  void set_variance(double value);
  private:
  double _internal_variance() const;
  void _internal_set_variance(double value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.sensor_proto.RelativeHumidity)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::galbot::core_proto::Header* header_;
  double relative_humidity_;
  double variance_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto;
};
// -------------------------------------------------------------------

class Temperature PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.sensor_proto.Temperature) */ {
 public:
  inline Temperature() : Temperature(nullptr) {}
  virtual ~Temperature();

  Temperature(const Temperature& from);
  Temperature(Temperature&& from) noexcept
    : Temperature() {
    *this = ::std::move(from);
  }

  inline Temperature& operator=(const Temperature& from) {
    CopyFrom(from);
    return *this;
  }
  inline Temperature& operator=(Temperature&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Temperature& default_instance();

  static inline const Temperature* internal_default_instance() {
    return reinterpret_cast<const Temperature*>(
               &_Temperature_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Temperature& a, Temperature& b) {
    a.Swap(&b);
  }
  inline void Swap(Temperature* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Temperature* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Temperature* New() const final {
    return CreateMaybeMessage<Temperature>(nullptr);
  }

  Temperature* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Temperature>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Temperature& from);
  void MergeFrom(const Temperature& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Temperature* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.sensor_proto.Temperature";
  }
  protected:
  explicit Temperature(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto);
    return ::descriptor_table_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kTemperatureFieldNumber = 2,
    kVarianceFieldNumber = 3,
  };
  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // double temperature = 2;
  void clear_temperature();
  double temperature() const;
  void set_temperature(double value);
  private:
  double _internal_temperature() const;
  void _internal_set_temperature(double value);
  public:

  // double variance = 3;
  void clear_variance();
  double variance() const;
  void set_variance(double value);
  private:
  double _internal_variance() const;
  void _internal_set_variance(double value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.sensor_proto.Temperature)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::galbot::core_proto::Header* header_;
  double temperature_;
  double variance_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FluidPressure

// .galbot.core_proto.Header header = 1;
inline bool FluidPressure::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool FluidPressure::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& FluidPressure::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& FluidPressure::header() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.FluidPressure.header)
  return _internal_header();
}
inline void FluidPressure::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.sensor_proto.FluidPressure.header)
}
inline ::galbot::core_proto::Header* FluidPressure::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* FluidPressure::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.sensor_proto.FluidPressure.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* FluidPressure::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* FluidPressure::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.sensor_proto.FluidPressure.header)
  return _internal_mutable_header();
}
inline void FluidPressure::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.sensor_proto.FluidPressure.header)
}

// double fluid_pressure = 2;
inline void FluidPressure::clear_fluid_pressure() {
  fluid_pressure_ = 0;
}
inline double FluidPressure::_internal_fluid_pressure() const {
  return fluid_pressure_;
}
inline double FluidPressure::fluid_pressure() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.FluidPressure.fluid_pressure)
  return _internal_fluid_pressure();
}
inline void FluidPressure::_internal_set_fluid_pressure(double value) {
  
  fluid_pressure_ = value;
}
inline void FluidPressure::set_fluid_pressure(double value) {
  _internal_set_fluid_pressure(value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.FluidPressure.fluid_pressure)
}

// double variance = 3;
inline void FluidPressure::clear_variance() {
  variance_ = 0;
}
inline double FluidPressure::_internal_variance() const {
  return variance_;
}
inline double FluidPressure::variance() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.FluidPressure.variance)
  return _internal_variance();
}
inline void FluidPressure::_internal_set_variance(double value) {
  
  variance_ = value;
}
inline void FluidPressure::set_variance(double value) {
  _internal_set_variance(value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.FluidPressure.variance)
}

// -------------------------------------------------------------------

// Illuminance

// .galbot.core_proto.Header header = 1;
inline bool Illuminance::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool Illuminance::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& Illuminance::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& Illuminance::header() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.Illuminance.header)
  return _internal_header();
}
inline void Illuminance::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.sensor_proto.Illuminance.header)
}
inline ::galbot::core_proto::Header* Illuminance::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* Illuminance::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.sensor_proto.Illuminance.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* Illuminance::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* Illuminance::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.sensor_proto.Illuminance.header)
  return _internal_mutable_header();
}
inline void Illuminance::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.sensor_proto.Illuminance.header)
}

// double illuminance = 2;
inline void Illuminance::clear_illuminance() {
  illuminance_ = 0;
}
inline double Illuminance::_internal_illuminance() const {
  return illuminance_;
}
inline double Illuminance::illuminance() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.Illuminance.illuminance)
  return _internal_illuminance();
}
inline void Illuminance::_internal_set_illuminance(double value) {
  
  illuminance_ = value;
}
inline void Illuminance::set_illuminance(double value) {
  _internal_set_illuminance(value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.Illuminance.illuminance)
}

// double variance = 3;
inline void Illuminance::clear_variance() {
  variance_ = 0;
}
inline double Illuminance::_internal_variance() const {
  return variance_;
}
inline double Illuminance::variance() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.Illuminance.variance)
  return _internal_variance();
}
inline void Illuminance::_internal_set_variance(double value) {
  
  variance_ = value;
}
inline void Illuminance::set_variance(double value) {
  _internal_set_variance(value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.Illuminance.variance)
}

// -------------------------------------------------------------------

// MagneticField

// .galbot.core_proto.Header header = 1;
inline bool MagneticField::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool MagneticField::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& MagneticField::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& MagneticField::header() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.MagneticField.header)
  return _internal_header();
}
inline void MagneticField::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.sensor_proto.MagneticField.header)
}
inline ::galbot::core_proto::Header* MagneticField::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* MagneticField::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.sensor_proto.MagneticField.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* MagneticField::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* MagneticField::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.sensor_proto.MagneticField.header)
  return _internal_mutable_header();
}
inline void MagneticField::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.sensor_proto.MagneticField.header)
}

// .galbot.core_proto.Vector3 magnetic_field = 2;
inline bool MagneticField::_internal_has_magnetic_field() const {
  return this != internal_default_instance() && magnetic_field_ != nullptr;
}
inline bool MagneticField::has_magnetic_field() const {
  return _internal_has_magnetic_field();
}
inline const ::galbot::core_proto::Vector3& MagneticField::_internal_magnetic_field() const {
  const ::galbot::core_proto::Vector3* p = magnetic_field_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Vector3&>(
      ::galbot::core_proto::_Vector3_default_instance_);
}
inline const ::galbot::core_proto::Vector3& MagneticField::magnetic_field() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.MagneticField.magnetic_field)
  return _internal_magnetic_field();
}
inline void MagneticField::unsafe_arena_set_allocated_magnetic_field(
    ::galbot::core_proto::Vector3* magnetic_field) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(magnetic_field_);
  }
  magnetic_field_ = magnetic_field;
  if (magnetic_field) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.sensor_proto.MagneticField.magnetic_field)
}
inline ::galbot::core_proto::Vector3* MagneticField::release_magnetic_field() {
  
  ::galbot::core_proto::Vector3* temp = magnetic_field_;
  magnetic_field_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Vector3* MagneticField::unsafe_arena_release_magnetic_field() {
  // @@protoc_insertion_point(field_release:galbot.sensor_proto.MagneticField.magnetic_field)
  
  ::galbot::core_proto::Vector3* temp = magnetic_field_;
  magnetic_field_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Vector3* MagneticField::_internal_mutable_magnetic_field() {
  
  if (magnetic_field_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Vector3>(GetArena());
    magnetic_field_ = p;
  }
  return magnetic_field_;
}
inline ::galbot::core_proto::Vector3* MagneticField::mutable_magnetic_field() {
  // @@protoc_insertion_point(field_mutable:galbot.sensor_proto.MagneticField.magnetic_field)
  return _internal_mutable_magnetic_field();
}
inline void MagneticField::set_allocated_magnetic_field(::galbot::core_proto::Vector3* magnetic_field) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(magnetic_field_);
  }
  if (magnetic_field) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(magnetic_field)->GetArena();
    if (message_arena != submessage_arena) {
      magnetic_field = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, magnetic_field, submessage_arena);
    }
    
  } else {
    
  }
  magnetic_field_ = magnetic_field;
  // @@protoc_insertion_point(field_set_allocated:galbot.sensor_proto.MagneticField.magnetic_field)
}

// .galbot.core_proto.Covariance3d magnetic_field_covariance = 3;
inline bool MagneticField::_internal_has_magnetic_field_covariance() const {
  return this != internal_default_instance() && magnetic_field_covariance_ != nullptr;
}
inline bool MagneticField::has_magnetic_field_covariance() const {
  return _internal_has_magnetic_field_covariance();
}
inline const ::galbot::core_proto::Covariance3d& MagneticField::_internal_magnetic_field_covariance() const {
  const ::galbot::core_proto::Covariance3d* p = magnetic_field_covariance_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Covariance3d&>(
      ::galbot::core_proto::_Covariance3d_default_instance_);
}
inline const ::galbot::core_proto::Covariance3d& MagneticField::magnetic_field_covariance() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.MagneticField.magnetic_field_covariance)
  return _internal_magnetic_field_covariance();
}
inline void MagneticField::unsafe_arena_set_allocated_magnetic_field_covariance(
    ::galbot::core_proto::Covariance3d* magnetic_field_covariance) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(magnetic_field_covariance_);
  }
  magnetic_field_covariance_ = magnetic_field_covariance;
  if (magnetic_field_covariance) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.sensor_proto.MagneticField.magnetic_field_covariance)
}
inline ::galbot::core_proto::Covariance3d* MagneticField::release_magnetic_field_covariance() {
  
  ::galbot::core_proto::Covariance3d* temp = magnetic_field_covariance_;
  magnetic_field_covariance_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Covariance3d* MagneticField::unsafe_arena_release_magnetic_field_covariance() {
  // @@protoc_insertion_point(field_release:galbot.sensor_proto.MagneticField.magnetic_field_covariance)
  
  ::galbot::core_proto::Covariance3d* temp = magnetic_field_covariance_;
  magnetic_field_covariance_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Covariance3d* MagneticField::_internal_mutable_magnetic_field_covariance() {
  
  if (magnetic_field_covariance_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Covariance3d>(GetArena());
    magnetic_field_covariance_ = p;
  }
  return magnetic_field_covariance_;
}
inline ::galbot::core_proto::Covariance3d* MagneticField::mutable_magnetic_field_covariance() {
  // @@protoc_insertion_point(field_mutable:galbot.sensor_proto.MagneticField.magnetic_field_covariance)
  return _internal_mutable_magnetic_field_covariance();
}
inline void MagneticField::set_allocated_magnetic_field_covariance(::galbot::core_proto::Covariance3d* magnetic_field_covariance) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(magnetic_field_covariance_);
  }
  if (magnetic_field_covariance) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(magnetic_field_covariance)->GetArena();
    if (message_arena != submessage_arena) {
      magnetic_field_covariance = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, magnetic_field_covariance, submessage_arena);
    }
    
  } else {
    
  }
  magnetic_field_covariance_ = magnetic_field_covariance;
  // @@protoc_insertion_point(field_set_allocated:galbot.sensor_proto.MagneticField.magnetic_field_covariance)
}

// -------------------------------------------------------------------

// RelativeHumidity

// .galbot.core_proto.Header header = 1;
inline bool RelativeHumidity::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool RelativeHumidity::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& RelativeHumidity::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& RelativeHumidity::header() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.RelativeHumidity.header)
  return _internal_header();
}
inline void RelativeHumidity::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.sensor_proto.RelativeHumidity.header)
}
inline ::galbot::core_proto::Header* RelativeHumidity::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* RelativeHumidity::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.sensor_proto.RelativeHumidity.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* RelativeHumidity::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* RelativeHumidity::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.sensor_proto.RelativeHumidity.header)
  return _internal_mutable_header();
}
inline void RelativeHumidity::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.sensor_proto.RelativeHumidity.header)
}

// double relative_humidity = 2;
inline void RelativeHumidity::clear_relative_humidity() {
  relative_humidity_ = 0;
}
inline double RelativeHumidity::_internal_relative_humidity() const {
  return relative_humidity_;
}
inline double RelativeHumidity::relative_humidity() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.RelativeHumidity.relative_humidity)
  return _internal_relative_humidity();
}
inline void RelativeHumidity::_internal_set_relative_humidity(double value) {
  
  relative_humidity_ = value;
}
inline void RelativeHumidity::set_relative_humidity(double value) {
  _internal_set_relative_humidity(value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.RelativeHumidity.relative_humidity)
}

// double variance = 3;
inline void RelativeHumidity::clear_variance() {
  variance_ = 0;
}
inline double RelativeHumidity::_internal_variance() const {
  return variance_;
}
inline double RelativeHumidity::variance() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.RelativeHumidity.variance)
  return _internal_variance();
}
inline void RelativeHumidity::_internal_set_variance(double value) {
  
  variance_ = value;
}
inline void RelativeHumidity::set_variance(double value) {
  _internal_set_variance(value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.RelativeHumidity.variance)
}

// -------------------------------------------------------------------

// Temperature

// .galbot.core_proto.Header header = 1;
inline bool Temperature::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool Temperature::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& Temperature::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& Temperature::header() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.Temperature.header)
  return _internal_header();
}
inline void Temperature::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.sensor_proto.Temperature.header)
}
inline ::galbot::core_proto::Header* Temperature::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* Temperature::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.sensor_proto.Temperature.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* Temperature::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* Temperature::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.sensor_proto.Temperature.header)
  return _internal_mutable_header();
}
inline void Temperature::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.sensor_proto.Temperature.header)
}

// double temperature = 2;
inline void Temperature::clear_temperature() {
  temperature_ = 0;
}
inline double Temperature::_internal_temperature() const {
  return temperature_;
}
inline double Temperature::temperature() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.Temperature.temperature)
  return _internal_temperature();
}
inline void Temperature::_internal_set_temperature(double value) {
  
  temperature_ = value;
}
inline void Temperature::set_temperature(double value) {
  _internal_set_temperature(value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.Temperature.temperature)
}

// double variance = 3;
inline void Temperature::clear_variance() {
  variance_ = 0;
}
inline double Temperature::_internal_variance() const {
  return variance_;
}
inline double Temperature::variance() const {
  // @@protoc_insertion_point(field_get:galbot.sensor_proto.Temperature.variance)
  return _internal_variance();
}
inline void Temperature::_internal_set_variance(double value) {
  
  variance_ = value;
}
inline void Temperature::set_variance(double value) {
  _internal_set_variance(value);
  // @@protoc_insertion_point(field_set:galbot.sensor_proto.Temperature.variance)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sensor_proto
}  // namespace galbot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fsensor_5fproto_2fphysical_5fquantity_2eproto
