// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/service_proto/fault.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fservice_5fproto_2ffault_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fservice_5fproto_2ffault_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "galbot/core_proto/header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fservice_5fproto_2ffault_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fservice_5fproto_2ffault_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fservice_5fproto_2ffault_2eproto;
namespace galbot {
namespace service_proto {
class FaultDetail;
class FaultDetailDefaultTypeInternal;
extern FaultDetailDefaultTypeInternal _FaultDetail_default_instance_;
}  // namespace service_proto
}  // namespace galbot
PROTOBUF_NAMESPACE_OPEN
template<> ::galbot::service_proto::FaultDetail* Arena::CreateMaybeMessage<::galbot::service_proto::FaultDetail>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace service_proto {

// ===================================================================

class FaultDetail PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.service_proto.FaultDetail) */ {
 public:
  inline FaultDetail() : FaultDetail(nullptr) {}
  virtual ~FaultDetail();

  FaultDetail(const FaultDetail& from);
  FaultDetail(FaultDetail&& from) noexcept
    : FaultDetail() {
    *this = ::std::move(from);
  }

  inline FaultDetail& operator=(const FaultDetail& from) {
    CopyFrom(from);
    return *this;
  }
  inline FaultDetail& operator=(FaultDetail&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FaultDetail& default_instance();

  static inline const FaultDetail* internal_default_instance() {
    return reinterpret_cast<const FaultDetail*>(
               &_FaultDetail_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FaultDetail& a, FaultDetail& b) {
    a.Swap(&b);
  }
  inline void Swap(FaultDetail* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FaultDetail* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FaultDetail* New() const final {
    return CreateMaybeMessage<FaultDetail>(nullptr);
  }

  FaultDetail* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FaultDetail>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FaultDetail& from);
  void MergeFrom(const FaultDetail& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FaultDetail* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.service_proto.FaultDetail";
  }
  protected:
  explicit FaultDetail(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fservice_5fproto_2ffault_2eproto);
    return ::descriptor_table_galbot_2fservice_5fproto_2ffault_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFaultDescriptionFieldNumber = 4,
    kFaultHandlingDescriptionFieldNumber = 9,
    kHeaderFieldNumber = 1,
    kFaultLevelFieldNumber = 2,
    kFaultScoreFieldNumber = 3,
    kFaultHandlingIdFieldNumber = 8,
  };
  // string fault_description = 4;
  void clear_fault_description();
  const std::string& fault_description() const;
  void set_fault_description(const std::string& value);
  void set_fault_description(std::string&& value);
  void set_fault_description(const char* value);
  void set_fault_description(const char* value, size_t size);
  std::string* mutable_fault_description();
  std::string* release_fault_description();
  void set_allocated_fault_description(std::string* fault_description);
  private:
  const std::string& _internal_fault_description() const;
  void _internal_set_fault_description(const std::string& value);
  std::string* _internal_mutable_fault_description();
  public:

  // string fault_handling_description = 9;
  void clear_fault_handling_description();
  const std::string& fault_handling_description() const;
  void set_fault_handling_description(const std::string& value);
  void set_fault_handling_description(std::string&& value);
  void set_fault_handling_description(const char* value);
  void set_fault_handling_description(const char* value, size_t size);
  std::string* mutable_fault_handling_description();
  std::string* release_fault_handling_description();
  void set_allocated_fault_handling_description(std::string* fault_handling_description);
  private:
  const std::string& _internal_fault_handling_description() const;
  void _internal_set_fault_handling_description(const std::string& value);
  std::string* _internal_mutable_fault_handling_description();
  public:

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // int32 fault_level = 2;
  void clear_fault_level();
  ::PROTOBUF_NAMESPACE_ID::int32 fault_level() const;
  void set_fault_level(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_fault_level() const;
  void _internal_set_fault_level(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 fault_score = 3 [deprecated = true];
  PROTOBUF_DEPRECATED void clear_fault_score();
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::int32 fault_score() const;
  PROTOBUF_DEPRECATED void set_fault_score(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_fault_score() const;
  void _internal_set_fault_score(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int64 fault_handling_id = 8;
  void clear_fault_handling_id();
  ::PROTOBUF_NAMESPACE_ID::int64 fault_handling_id() const;
  void set_fault_handling_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_fault_handling_id() const;
  void _internal_set_fault_handling_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.service_proto.FaultDetail)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fault_description_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fault_handling_description_;
  ::galbot::core_proto::Header* header_;
  ::PROTOBUF_NAMESPACE_ID::int32 fault_level_;
  ::PROTOBUF_NAMESPACE_ID::int32 fault_score_;
  ::PROTOBUF_NAMESPACE_ID::int64 fault_handling_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fservice_5fproto_2ffault_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FaultDetail

// .galbot.core_proto.Header header = 1;
inline bool FaultDetail::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool FaultDetail::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& FaultDetail::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& FaultDetail::header() const {
  // @@protoc_insertion_point(field_get:galbot.service_proto.FaultDetail.header)
  return _internal_header();
}
inline void FaultDetail::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.service_proto.FaultDetail.header)
}
inline ::galbot::core_proto::Header* FaultDetail::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* FaultDetail::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.service_proto.FaultDetail.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* FaultDetail::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* FaultDetail::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.service_proto.FaultDetail.header)
  return _internal_mutable_header();
}
inline void FaultDetail::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.service_proto.FaultDetail.header)
}

// int32 fault_level = 2;
inline void FaultDetail::clear_fault_level() {
  fault_level_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FaultDetail::_internal_fault_level() const {
  return fault_level_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FaultDetail::fault_level() const {
  // @@protoc_insertion_point(field_get:galbot.service_proto.FaultDetail.fault_level)
  return _internal_fault_level();
}
inline void FaultDetail::_internal_set_fault_level(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  fault_level_ = value;
}
inline void FaultDetail::set_fault_level(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_fault_level(value);
  // @@protoc_insertion_point(field_set:galbot.service_proto.FaultDetail.fault_level)
}

// int32 fault_score = 3 [deprecated = true];
inline void FaultDetail::clear_fault_score() {
  fault_score_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FaultDetail::_internal_fault_score() const {
  return fault_score_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FaultDetail::fault_score() const {
  // @@protoc_insertion_point(field_get:galbot.service_proto.FaultDetail.fault_score)
  return _internal_fault_score();
}
inline void FaultDetail::_internal_set_fault_score(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  fault_score_ = value;
}
inline void FaultDetail::set_fault_score(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_fault_score(value);
  // @@protoc_insertion_point(field_set:galbot.service_proto.FaultDetail.fault_score)
}

// string fault_description = 4;
inline void FaultDetail::clear_fault_description() {
  fault_description_.ClearToEmpty();
}
inline const std::string& FaultDetail::fault_description() const {
  // @@protoc_insertion_point(field_get:galbot.service_proto.FaultDetail.fault_description)
  return _internal_fault_description();
}
inline void FaultDetail::set_fault_description(const std::string& value) {
  _internal_set_fault_description(value);
  // @@protoc_insertion_point(field_set:galbot.service_proto.FaultDetail.fault_description)
}
inline std::string* FaultDetail::mutable_fault_description() {
  // @@protoc_insertion_point(field_mutable:galbot.service_proto.FaultDetail.fault_description)
  return _internal_mutable_fault_description();
}
inline const std::string& FaultDetail::_internal_fault_description() const {
  return fault_description_.Get();
}
inline void FaultDetail::_internal_set_fault_description(const std::string& value) {
  
  fault_description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void FaultDetail::set_fault_description(std::string&& value) {
  
  fault_description_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.service_proto.FaultDetail.fault_description)
}
inline void FaultDetail::set_fault_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  fault_description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.service_proto.FaultDetail.fault_description)
}
inline void FaultDetail::set_fault_description(const char* value,
    size_t size) {
  
  fault_description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.service_proto.FaultDetail.fault_description)
}
inline std::string* FaultDetail::_internal_mutable_fault_description() {
  
  return fault_description_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* FaultDetail::release_fault_description() {
  // @@protoc_insertion_point(field_release:galbot.service_proto.FaultDetail.fault_description)
  return fault_description_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FaultDetail::set_allocated_fault_description(std::string* fault_description) {
  if (fault_description != nullptr) {
    
  } else {
    
  }
  fault_description_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fault_description,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.service_proto.FaultDetail.fault_description)
}

// int64 fault_handling_id = 8;
inline void FaultDetail::clear_fault_handling_id() {
  fault_handling_id_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 FaultDetail::_internal_fault_handling_id() const {
  return fault_handling_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 FaultDetail::fault_handling_id() const {
  // @@protoc_insertion_point(field_get:galbot.service_proto.FaultDetail.fault_handling_id)
  return _internal_fault_handling_id();
}
inline void FaultDetail::_internal_set_fault_handling_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  fault_handling_id_ = value;
}
inline void FaultDetail::set_fault_handling_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_fault_handling_id(value);
  // @@protoc_insertion_point(field_set:galbot.service_proto.FaultDetail.fault_handling_id)
}

// string fault_handling_description = 9;
inline void FaultDetail::clear_fault_handling_description() {
  fault_handling_description_.ClearToEmpty();
}
inline const std::string& FaultDetail::fault_handling_description() const {
  // @@protoc_insertion_point(field_get:galbot.service_proto.FaultDetail.fault_handling_description)
  return _internal_fault_handling_description();
}
inline void FaultDetail::set_fault_handling_description(const std::string& value) {
  _internal_set_fault_handling_description(value);
  // @@protoc_insertion_point(field_set:galbot.service_proto.FaultDetail.fault_handling_description)
}
inline std::string* FaultDetail::mutable_fault_handling_description() {
  // @@protoc_insertion_point(field_mutable:galbot.service_proto.FaultDetail.fault_handling_description)
  return _internal_mutable_fault_handling_description();
}
inline const std::string& FaultDetail::_internal_fault_handling_description() const {
  return fault_handling_description_.Get();
}
inline void FaultDetail::_internal_set_fault_handling_description(const std::string& value) {
  
  fault_handling_description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void FaultDetail::set_fault_handling_description(std::string&& value) {
  
  fault_handling_description_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.service_proto.FaultDetail.fault_handling_description)
}
inline void FaultDetail::set_fault_handling_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  fault_handling_description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.service_proto.FaultDetail.fault_handling_description)
}
inline void FaultDetail::set_fault_handling_description(const char* value,
    size_t size) {
  
  fault_handling_description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.service_proto.FaultDetail.fault_handling_description)
}
inline std::string* FaultDetail::_internal_mutable_fault_handling_description() {
  
  return fault_handling_description_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* FaultDetail::release_fault_handling_description() {
  // @@protoc_insertion_point(field_release:galbot.service_proto.FaultDetail.fault_handling_description)
  return fault_handling_description_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FaultDetail::set_allocated_fault_handling_description(std::string* fault_handling_description) {
  if (fault_handling_description != nullptr) {
    
  } else {
    
  }
  fault_handling_description_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fault_handling_description,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.service_proto.FaultDetail.fault_handling_description)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace service_proto
}  // namespace galbot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fservice_5fproto_2ffault_2eproto
