// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/service_proto/service_state.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fservice_5fproto_2fservice_5fstate_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fservice_5fproto_2fservice_5fstate_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "galbot/core_proto/header.pb.h"
#include "galbot/service_proto/fault.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fservice_5fproto_2fservice_5fstate_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fservice_5fproto_2fservice_5fstate_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fservice_5fproto_2fservice_5fstate_2eproto;
namespace galbot {
namespace service_proto {
class ServiceState;
class ServiceStateDefaultTypeInternal;
extern ServiceStateDefaultTypeInternal _ServiceState_default_instance_;
class ServiceState_FaultMapEntry_DoNotUse;
class ServiceState_FaultMapEntry_DoNotUseDefaultTypeInternal;
extern ServiceState_FaultMapEntry_DoNotUseDefaultTypeInternal _ServiceState_FaultMapEntry_DoNotUse_default_instance_;
}  // namespace service_proto
}  // namespace galbot
PROTOBUF_NAMESPACE_OPEN
template<> ::galbot::service_proto::ServiceState* Arena::CreateMaybeMessage<::galbot::service_proto::ServiceState>(Arena*);
template<> ::galbot::service_proto::ServiceState_FaultMapEntry_DoNotUse* Arena::CreateMaybeMessage<::galbot::service_proto::ServiceState_FaultMapEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace service_proto {

enum ServiceState_StateEnum : int {
  ServiceState_StateEnum_UNKNOWN = 0,
  ServiceState_StateEnum_INITIALIZING = 1,
  ServiceState_StateEnum_INIT_FAILED = 2,
  ServiceState_StateEnum_RUNNING = 3,
  ServiceState_StateEnum_ABNORMAL = 4,
  ServiceState_StateEnum_EXTEND_STATE = 5,
  ServiceState_StateEnum_ServiceState_StateEnum_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ServiceState_StateEnum_ServiceState_StateEnum_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ServiceState_StateEnum_IsValid(int value);
constexpr ServiceState_StateEnum ServiceState_StateEnum_StateEnum_MIN = ServiceState_StateEnum_UNKNOWN;
constexpr ServiceState_StateEnum ServiceState_StateEnum_StateEnum_MAX = ServiceState_StateEnum_EXTEND_STATE;
constexpr int ServiceState_StateEnum_StateEnum_ARRAYSIZE = ServiceState_StateEnum_StateEnum_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ServiceState_StateEnum_descriptor();
template<typename T>
inline const std::string& ServiceState_StateEnum_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ServiceState_StateEnum>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ServiceState_StateEnum_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ServiceState_StateEnum_descriptor(), enum_t_value);
}
inline bool ServiceState_StateEnum_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ServiceState_StateEnum* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ServiceState_StateEnum>(
    ServiceState_StateEnum_descriptor(), name, value);
}
// ===================================================================

class ServiceState_FaultMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<ServiceState_FaultMapEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int64, ::galbot::service_proto::FaultDetail,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<ServiceState_FaultMapEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int64, ::galbot::service_proto::FaultDetail,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  ServiceState_FaultMapEntry_DoNotUse();
  explicit ServiceState_FaultMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const ServiceState_FaultMapEntry_DoNotUse& other);
  static const ServiceState_FaultMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ServiceState_FaultMapEntry_DoNotUse*>(&_ServiceState_FaultMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fservice_5fproto_2fservice_5fstate_2eproto);
    return ::descriptor_table_galbot_2fservice_5fproto_2fservice_5fstate_2eproto.file_level_metadata[0];
  }

  public:
};

// -------------------------------------------------------------------

class ServiceState PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.service_proto.ServiceState) */ {
 public:
  inline ServiceState() : ServiceState(nullptr) {}
  virtual ~ServiceState();

  ServiceState(const ServiceState& from);
  ServiceState(ServiceState&& from) noexcept
    : ServiceState() {
    *this = ::std::move(from);
  }

  inline ServiceState& operator=(const ServiceState& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServiceState& operator=(ServiceState&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ServiceState& default_instance();

  static inline const ServiceState* internal_default_instance() {
    return reinterpret_cast<const ServiceState*>(
               &_ServiceState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ServiceState& a, ServiceState& b) {
    a.Swap(&b);
  }
  inline void Swap(ServiceState* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServiceState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServiceState* New() const final {
    return CreateMaybeMessage<ServiceState>(nullptr);
  }

  ServiceState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServiceState>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ServiceState& from);
  void MergeFrom(const ServiceState& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServiceState* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.service_proto.ServiceState";
  }
  protected:
  explicit ServiceState(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fservice_5fproto_2fservice_5fstate_2eproto);
    return ::descriptor_table_galbot_2fservice_5fproto_2fservice_5fstate_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  typedef ServiceState_StateEnum StateEnum;
  static constexpr StateEnum UNKNOWN =
    ServiceState_StateEnum_UNKNOWN;
  static constexpr StateEnum INITIALIZING =
    ServiceState_StateEnum_INITIALIZING;
  static constexpr StateEnum INIT_FAILED =
    ServiceState_StateEnum_INIT_FAILED;
  static constexpr StateEnum RUNNING =
    ServiceState_StateEnum_RUNNING;
  static constexpr StateEnum ABNORMAL =
    ServiceState_StateEnum_ABNORMAL;
  static constexpr StateEnum EXTEND_STATE =
    ServiceState_StateEnum_EXTEND_STATE;
  static inline bool StateEnum_IsValid(int value) {
    return ServiceState_StateEnum_IsValid(value);
  }
  static constexpr StateEnum StateEnum_MIN =
    ServiceState_StateEnum_StateEnum_MIN;
  static constexpr StateEnum StateEnum_MAX =
    ServiceState_StateEnum_StateEnum_MAX;
  static constexpr int StateEnum_ARRAYSIZE =
    ServiceState_StateEnum_StateEnum_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  StateEnum_descriptor() {
    return ServiceState_StateEnum_descriptor();
  }
  template<typename T>
  static inline const std::string& StateEnum_Name(T enum_t_value) {
    static_assert(::std::is_same<T, StateEnum>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function StateEnum_Name.");
    return ServiceState_StateEnum_Name(enum_t_value);
  }
  static inline bool StateEnum_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      StateEnum* value) {
    return ServiceState_StateEnum_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kFaultMapFieldNumber = 8,
    kServiceNameFieldNumber = 2,
    kVersionFieldNumber = 3,
    kDescriptionFieldNumber = 5,
    kExtendStateFieldNumber = 6,
    kHeaderFieldNumber = 1,
    kStateFieldNumber = 4,
  };
  // map<int64, .galbot.service_proto.FaultDetail> fault_map = 8 [deprecated = true];
  PROTOBUF_DEPRECATED int fault_map_size() const;
  private:
  int _internal_fault_map_size() const;
  public:
  PROTOBUF_DEPRECATED void clear_fault_map();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int64, ::galbot::service_proto::FaultDetail >&
      _internal_fault_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int64, ::galbot::service_proto::FaultDetail >*
      _internal_mutable_fault_map();
  public:
  PROTOBUF_DEPRECATED const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int64, ::galbot::service_proto::FaultDetail >&
      fault_map() const;
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int64, ::galbot::service_proto::FaultDetail >*
      mutable_fault_map();

  // string service_name = 2;
  void clear_service_name();
  const std::string& service_name() const;
  void set_service_name(const std::string& value);
  void set_service_name(std::string&& value);
  void set_service_name(const char* value);
  void set_service_name(const char* value, size_t size);
  std::string* mutable_service_name();
  std::string* release_service_name();
  void set_allocated_service_name(std::string* service_name);
  private:
  const std::string& _internal_service_name() const;
  void _internal_set_service_name(const std::string& value);
  std::string* _internal_mutable_service_name();
  public:

  // string version = 3;
  void clear_version();
  const std::string& version() const;
  void set_version(const std::string& value);
  void set_version(std::string&& value);
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  std::string* mutable_version();
  std::string* release_version();
  void set_allocated_version(std::string* version);
  private:
  const std::string& _internal_version() const;
  void _internal_set_version(const std::string& value);
  std::string* _internal_mutable_version();
  public:

  // string description = 5;
  void clear_description();
  const std::string& description() const;
  void set_description(const std::string& value);
  void set_description(std::string&& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  std::string* mutable_description();
  std::string* release_description();
  void set_allocated_description(std::string* description);
  private:
  const std::string& _internal_description() const;
  void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // string extend_state = 6;
  void clear_extend_state();
  const std::string& extend_state() const;
  void set_extend_state(const std::string& value);
  void set_extend_state(std::string&& value);
  void set_extend_state(const char* value);
  void set_extend_state(const char* value, size_t size);
  std::string* mutable_extend_state();
  std::string* release_extend_state();
  void set_allocated_extend_state(std::string* extend_state);
  private:
  const std::string& _internal_extend_state() const;
  void _internal_set_extend_state(const std::string& value);
  std::string* _internal_mutable_extend_state();
  public:

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // .galbot.service_proto.ServiceState.StateEnum state = 4;
  void clear_state();
  ::galbot::service_proto::ServiceState_StateEnum state() const;
  void set_state(::galbot::service_proto::ServiceState_StateEnum value);
  private:
  ::galbot::service_proto::ServiceState_StateEnum _internal_state() const;
  void _internal_set_state(::galbot::service_proto::ServiceState_StateEnum value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.service_proto.ServiceState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      ServiceState_FaultMapEntry_DoNotUse,
      ::PROTOBUF_NAMESPACE_ID::int64, ::galbot::service_proto::FaultDetail,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> fault_map_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr extend_state_;
  ::galbot::core_proto::Header* header_;
  int state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fservice_5fproto_2fservice_5fstate_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ServiceState

// .galbot.core_proto.Header header = 1;
inline bool ServiceState::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool ServiceState::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& ServiceState::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& ServiceState::header() const {
  // @@protoc_insertion_point(field_get:galbot.service_proto.ServiceState.header)
  return _internal_header();
}
inline void ServiceState::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.service_proto.ServiceState.header)
}
inline ::galbot::core_proto::Header* ServiceState::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* ServiceState::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.service_proto.ServiceState.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* ServiceState::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* ServiceState::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.service_proto.ServiceState.header)
  return _internal_mutable_header();
}
inline void ServiceState::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.service_proto.ServiceState.header)
}

// string service_name = 2;
inline void ServiceState::clear_service_name() {
  service_name_.ClearToEmpty();
}
inline const std::string& ServiceState::service_name() const {
  // @@protoc_insertion_point(field_get:galbot.service_proto.ServiceState.service_name)
  return _internal_service_name();
}
inline void ServiceState::set_service_name(const std::string& value) {
  _internal_set_service_name(value);
  // @@protoc_insertion_point(field_set:galbot.service_proto.ServiceState.service_name)
}
inline std::string* ServiceState::mutable_service_name() {
  // @@protoc_insertion_point(field_mutable:galbot.service_proto.ServiceState.service_name)
  return _internal_mutable_service_name();
}
inline const std::string& ServiceState::_internal_service_name() const {
  return service_name_.Get();
}
inline void ServiceState::_internal_set_service_name(const std::string& value) {
  
  service_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ServiceState::set_service_name(std::string&& value) {
  
  service_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.service_proto.ServiceState.service_name)
}
inline void ServiceState::set_service_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  service_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.service_proto.ServiceState.service_name)
}
inline void ServiceState::set_service_name(const char* value,
    size_t size) {
  
  service_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.service_proto.ServiceState.service_name)
}
inline std::string* ServiceState::_internal_mutable_service_name() {
  
  return service_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ServiceState::release_service_name() {
  // @@protoc_insertion_point(field_release:galbot.service_proto.ServiceState.service_name)
  return service_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServiceState::set_allocated_service_name(std::string* service_name) {
  if (service_name != nullptr) {
    
  } else {
    
  }
  service_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), service_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.service_proto.ServiceState.service_name)
}

// string version = 3;
inline void ServiceState::clear_version() {
  version_.ClearToEmpty();
}
inline const std::string& ServiceState::version() const {
  // @@protoc_insertion_point(field_get:galbot.service_proto.ServiceState.version)
  return _internal_version();
}
inline void ServiceState::set_version(const std::string& value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:galbot.service_proto.ServiceState.version)
}
inline std::string* ServiceState::mutable_version() {
  // @@protoc_insertion_point(field_mutable:galbot.service_proto.ServiceState.version)
  return _internal_mutable_version();
}
inline const std::string& ServiceState::_internal_version() const {
  return version_.Get();
}
inline void ServiceState::_internal_set_version(const std::string& value) {
  
  version_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ServiceState::set_version(std::string&& value) {
  
  version_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.service_proto.ServiceState.version)
}
inline void ServiceState::set_version(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  version_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.service_proto.ServiceState.version)
}
inline void ServiceState::set_version(const char* value,
    size_t size) {
  
  version_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.service_proto.ServiceState.version)
}
inline std::string* ServiceState::_internal_mutable_version() {
  
  return version_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ServiceState::release_version() {
  // @@protoc_insertion_point(field_release:galbot.service_proto.ServiceState.version)
  return version_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServiceState::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    
  } else {
    
  }
  version_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), version,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.service_proto.ServiceState.version)
}

// .galbot.service_proto.ServiceState.StateEnum state = 4;
inline void ServiceState::clear_state() {
  state_ = 0;
}
inline ::galbot::service_proto::ServiceState_StateEnum ServiceState::_internal_state() const {
  return static_cast< ::galbot::service_proto::ServiceState_StateEnum >(state_);
}
inline ::galbot::service_proto::ServiceState_StateEnum ServiceState::state() const {
  // @@protoc_insertion_point(field_get:galbot.service_proto.ServiceState.state)
  return _internal_state();
}
inline void ServiceState::_internal_set_state(::galbot::service_proto::ServiceState_StateEnum value) {
  
  state_ = value;
}
inline void ServiceState::set_state(::galbot::service_proto::ServiceState_StateEnum value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:galbot.service_proto.ServiceState.state)
}

// string description = 5;
inline void ServiceState::clear_description() {
  description_.ClearToEmpty();
}
inline const std::string& ServiceState::description() const {
  // @@protoc_insertion_point(field_get:galbot.service_proto.ServiceState.description)
  return _internal_description();
}
inline void ServiceState::set_description(const std::string& value) {
  _internal_set_description(value);
  // @@protoc_insertion_point(field_set:galbot.service_proto.ServiceState.description)
}
inline std::string* ServiceState::mutable_description() {
  // @@protoc_insertion_point(field_mutable:galbot.service_proto.ServiceState.description)
  return _internal_mutable_description();
}
inline const std::string& ServiceState::_internal_description() const {
  return description_.Get();
}
inline void ServiceState::_internal_set_description(const std::string& value) {
  
  description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ServiceState::set_description(std::string&& value) {
  
  description_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.service_proto.ServiceState.description)
}
inline void ServiceState::set_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.service_proto.ServiceState.description)
}
inline void ServiceState::set_description(const char* value,
    size_t size) {
  
  description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.service_proto.ServiceState.description)
}
inline std::string* ServiceState::_internal_mutable_description() {
  
  return description_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ServiceState::release_description() {
  // @@protoc_insertion_point(field_release:galbot.service_proto.ServiceState.description)
  return description_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServiceState::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  description_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), description,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.service_proto.ServiceState.description)
}

// string extend_state = 6;
inline void ServiceState::clear_extend_state() {
  extend_state_.ClearToEmpty();
}
inline const std::string& ServiceState::extend_state() const {
  // @@protoc_insertion_point(field_get:galbot.service_proto.ServiceState.extend_state)
  return _internal_extend_state();
}
inline void ServiceState::set_extend_state(const std::string& value) {
  _internal_set_extend_state(value);
  // @@protoc_insertion_point(field_set:galbot.service_proto.ServiceState.extend_state)
}
inline std::string* ServiceState::mutable_extend_state() {
  // @@protoc_insertion_point(field_mutable:galbot.service_proto.ServiceState.extend_state)
  return _internal_mutable_extend_state();
}
inline const std::string& ServiceState::_internal_extend_state() const {
  return extend_state_.Get();
}
inline void ServiceState::_internal_set_extend_state(const std::string& value) {
  
  extend_state_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ServiceState::set_extend_state(std::string&& value) {
  
  extend_state_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.service_proto.ServiceState.extend_state)
}
inline void ServiceState::set_extend_state(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  extend_state_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.service_proto.ServiceState.extend_state)
}
inline void ServiceState::set_extend_state(const char* value,
    size_t size) {
  
  extend_state_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.service_proto.ServiceState.extend_state)
}
inline std::string* ServiceState::_internal_mutable_extend_state() {
  
  return extend_state_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ServiceState::release_extend_state() {
  // @@protoc_insertion_point(field_release:galbot.service_proto.ServiceState.extend_state)
  return extend_state_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServiceState::set_allocated_extend_state(std::string* extend_state) {
  if (extend_state != nullptr) {
    
  } else {
    
  }
  extend_state_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), extend_state,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.service_proto.ServiceState.extend_state)
}

// map<int64, .galbot.service_proto.FaultDetail> fault_map = 8 [deprecated = true];
inline int ServiceState::_internal_fault_map_size() const {
  return fault_map_.size();
}
inline int ServiceState::fault_map_size() const {
  return _internal_fault_map_size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int64, ::galbot::service_proto::FaultDetail >&
ServiceState::_internal_fault_map() const {
  return fault_map_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int64, ::galbot::service_proto::FaultDetail >&
ServiceState::fault_map() const {
  // @@protoc_insertion_point(field_map:galbot.service_proto.ServiceState.fault_map)
  return _internal_fault_map();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int64, ::galbot::service_proto::FaultDetail >*
ServiceState::_internal_mutable_fault_map() {
  return fault_map_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int64, ::galbot::service_proto::FaultDetail >*
ServiceState::mutable_fault_map() {
  // @@protoc_insertion_point(field_mutable_map:galbot.service_proto.ServiceState.fault_map)
  return _internal_mutable_fault_map();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace service_proto
}  // namespace galbot

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::galbot::service_proto::ServiceState_StateEnum> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::galbot::service_proto::ServiceState_StateEnum>() {
  return ::galbot::service_proto::ServiceState_StateEnum_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fservice_5fproto_2fservice_5fstate_2eproto
